# -*- coding: utf-8 -*-

# Copyright (c) 2026, RTE (http://www.rte-france.com)
# See AUTHORS.txt
# All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of Dynawo, a hybrid C++/Modelica open source suite
# of simulation tools for power systems.

from content.Ticket import ticket

# Rename WECC parameters with a name that refers to the subcomponent

@ticket(4063)
def update(jobs):
    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "WTG4AWeccCurrentSource")
    for wecc in weccs:
        value = wecc.parset.get_param_value("WTG4A_PMaxPu")
        wecc.parset.remove_param_or_ref("WTG4A_PMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_PMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_PMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_PMinPu")
        wecc.parset.remove_param_or_ref("WTG4A_PMinPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_PMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_PMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_QMaxPu")
        wecc.parset.remove_param_or_ref("WTG4A_QMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_QMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_QMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_QMinPu")
        wecc.parset.remove_param_or_ref("WTG4A_QMinPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_QMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_QMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_tP")
        wecc.parset.remove_param_or_ref("WTG4A_tP")
        wecc.parset.add_param("DOUBLE", "WTG4A_tpREEC", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_tpREPC", value)
        value = wecc.parset.get_param_value("WTG4A_tp")
        wecc.parset.remove_param_or_ref("WTG4A_tp")
        wecc.parset.add_param("DOUBLE", "WTG4A_tpWTGTb", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "BESSWeccCurrentSource")
    for wecc in weccs:
        value = wecc.parset.get_param_value("BESS_PMaxPu")
        wecc.parset.remove_param_or_ref("BESS_PMaxPu")
        wecc.parset.add_param("DOUBLE", "BESS_PMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "BESS_PMaxREPCPu", value)
        value = wecc.parset.get_param_value("BESS_PMinPu")
        wecc.parset.remove_param_or_ref("BESS_PMinPu")
        wecc.parset.add_param("DOUBLE", "BESS_PMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "BESS_PMinREPCPu", value)
        value = wecc.parset.get_param_value("BESS_QMaxPu")
        wecc.parset.remove_param_or_ref("BESS_QMaxPu")
        wecc.parset.add_param("DOUBLE", "BESS_QMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "BESS_QMaxREPCPu", value)
        value = wecc.parset.get_param_value("BESS_QMinPu")
        wecc.parset.remove_param_or_ref("BESS_QMinPu")
        wecc.parset.add_param("DOUBLE", "BESS_QMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "BESS_QMinREPCPu", value)
        value = wecc.parset.get_param_value("BESS_tP")
        wecc.parset.remove_param_or_ref("BESS_tP")
        wecc.parset.add_param("DOUBLE", "BESS_tpREEC", value)
        wecc.parset.add_param("DOUBLE", "BESS_tpREPC", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "BESSWeccCurrentSourceNoPlantControl")
    for wecc in weccs:
        value = wecc.parset.get_param_value("BESS_PMaxPu")
        wecc.parset.remove_param_or_ref("BESS_PMaxPu")
        wecc.parset.add_param("DOUBLE", "BESS_PMaxREECPu", value)
        value = wecc.parset.get_param_value("BESS_PMinPu")
        wecc.parset.remove_param_or_ref("BESS_PMinPu")
        wecc.parset.add_param("DOUBLE", "BESS_PMinREECPu", value)
        value = wecc.parset.get_param_value("BESS_QMaxPu")
        wecc.parset.remove_param_or_ref("BESS_QMaxPu")
        wecc.parset.add_param("DOUBLE", "BESS_QMaxREECPu", value)
        value = wecc.parset.get_param_value("BESS_QMinPu")
        wecc.parset.remove_param_or_ref("BESS_QMinPu")
        wecc.parset.add_param("DOUBLE", "BESS_QMinREECPu", value)
        value = wecc.parset.get_param_value("BESS_tP")
        wecc.parset.remove_param_or_ref("BESS_tP")
        wecc.parset.add_param("DOUBLE", "BESS_tpREEC", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "PhotovoltaicsWeccCurrentSource" or "PhotovoltaicsWeccVoltageSource" in bbm.get_lib_name())
    for wecc in weccs:
        value = wecc.parset.get_param_value("photovoltaics_PMaxPu")
        wecc.parset.remove_param_or_ref("photovoltaics_PMaxPu")
        wecc.parset.add_param("DOUBLE", "photovoltaics_PMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "photovoltaics_PMaxREPCPu", value)
        value = wecc.parset.get_param_value("photovoltaics_PMinPu")
        wecc.parset.remove_param_or_ref("photovoltaics_PMinPu")
        wecc.parset.add_param("DOUBLE", "photovoltaics_PMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "photovoltaics_PMinREPCPu", value)
        value = wecc.parset.get_param_value("photovoltaics_QMaxPu")
        wecc.parset.remove_param_or_ref("photovoltaics_QMaxPu")
        wecc.parset.add_param("DOUBLE", "photovoltaics_QMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "photovoltaics_QMaxREPCPu", value)
        value = wecc.parset.get_param_value("photovoltaics_QMinPu")
        wecc.parset.remove_param_or_ref("photovoltaics_QMinPu")
        wecc.parset.add_param("DOUBLE", "photovoltaics_QMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "photovoltaics_QMinREPCPu", value)
        value = wecc.parset.get_param_value("photovoltaics_tP")
        wecc.parset.remove_param_or_ref("photovoltaics_tP")
        wecc.parset.add_param("DOUBLE", "photovoltaics_tpREEC", value)
        wecc.parset.add_param("DOUBLE", "photovoltaics_tpREPC", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "WT4BWeccCurrentSource")
    for wecc in weccs:
        value = wecc.parset.get_param_value("WT4B_PMaxPu")
        wecc.parset.remove_param_or_ref("WT4B_PMaxPu")
        wecc.parset.add_param("DOUBLE", "WT4B_PMaxREECPu", value)
        value = wecc.parset.get_param_value("WT4B_PMinPu")
        wecc.parset.remove_param_or_ref("WT4B_PMinPu")
        wecc.parset.add_param("DOUBLE", "WT4B_PMinREECPu", value)
        value = wecc.parset.get_param_value("WT4B_QMaxPu")
        wecc.parset.remove_param_or_ref("WT4B_QMaxPu")
        wecc.parset.add_param("DOUBLE", "WT4B_QMaxREECPu", value)
        value = wecc.parset.get_param_value("WT4B_QMinPu")
        wecc.parset.remove_param_or_ref("WT4B_QMinPu")
        wecc.parset.add_param("DOUBLE", "WT4B_QMinREECPu", value)
        value = wecc.parset.get_param_value("WT4B_tP")
        wecc.parset.remove_param_or_ref("WT4B_tP")
        wecc.parset.add_param("DOUBLE", "WT4B_tpREEC", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: "WTG3WeccCurrentSource" in bbm.get_lib_name())
    for wecc in weccs:
        value = wecc.parset.get_param_value("WTG3_PMaxPu")
        wecc.parset.remove_param_or_ref("WTG3_PMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG3_PMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG3_PMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG3_PMinPu")
        wecc.parset.remove_param_or_ref("WTG3_PMinPu")
        wecc.parset.add_param("DOUBLE", "WTG3_PMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG3_PMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG3_QMaxPu")
        wecc.parset.remove_param_or_ref("WTG3_QMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG3_QMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG3_QMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG3_QMinPu")
        wecc.parset.remove_param_or_ref("WTG3_QMinPu")
        wecc.parset.add_param("DOUBLE", "WTG3_QMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG3_QMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG3_tP")
        wecc.parset.remove_param_or_ref("WTG3_tP")
        wecc.parset.add_param("DOUBLE", "WTG3_tpREEC", value)
        wecc.parset.add_param("DOUBLE", "WTG3_tpREPC", value)
        value = wecc.parset.get_param_value("WTG3_tp")
        wecc.parset.remove_param_or_ref("WTG3_tp")
        wecc.parset.add_param("DOUBLE", "WTG3_tpWTGQa", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "WTG4AWeccCurrentSource")
    for wecc in weccs:
        value = wecc.parset.get_param_value("WTG4A_PMaxPu")
        wecc.parset.remove_param_or_ref("WTG4A_PMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_PMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_PMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_PMinPu")
        wecc.parset.remove_param_or_ref("WTG4A_PMinPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_PMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_PMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_QMaxPu")
        wecc.parset.remove_param_or_ref("WTG4A_QMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_QMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_QMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_QMinPu")
        wecc.parset.remove_param_or_ref("WTG4A_QMinPu")
        wecc.parset.add_param("DOUBLE", "WTG4A_QMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_QMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG4A_tP")
        wecc.parset.remove_param_or_ref("WTG4A_tP")
        wecc.parset.add_param("DOUBLE", "WTG4A_tpREEC", value)
        wecc.parset.add_param("DOUBLE", "WTG4A_tpREPC", value)
        value = wecc.parset.get_param_value("WTG4A_tp")
        wecc.parset.remove_param_or_ref("WTG4A_tp")
        wecc.parset.add_param("DOUBLE", "WTG4A_tpWTGTb", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "WTG4BWeccCurrentSource")
    for wecc in weccs:
        value = wecc.parset.get_param_value("WTG4B_PMaxPu")
        wecc.parset.remove_param_or_ref("WTG4B_PMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG4B_PMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4B_PMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG4B_PMinPu")
        wecc.parset.remove_param_or_ref("WTG4B_PMinPu")
        wecc.parset.add_param("DOUBLE", "WTG4B_PMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4B_PMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG4B_QMaxPu")
        wecc.parset.remove_param_or_ref("WTG4B_QMaxPu")
        wecc.parset.add_param("DOUBLE", "WTG4B_QMaxREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4B_QMaxREPCPu", value)
        value = wecc.parset.get_param_value("WTG4B_QMinPu")
        wecc.parset.remove_param_or_ref("WTG4B_QMinPu")
        wecc.parset.add_param("DOUBLE", "WTG4B_QMinREECPu", value)
        wecc.parset.add_param("DOUBLE", "WTG4B_QMinREPCPu", value)
        value = wecc.parset.get_param_value("WTG4B_tP")
        wecc.parset.remove_param_or_ref("WTG4B_tP")
        wecc.parset.add_param("DOUBLE", "WTG4B_tpREEC", value)
        wecc.parset.add_param("DOUBLE", "WTG4B_tpREPC", value)

    weccs = jobs.dyds.get_bbms(lambda bbm: bbm.get_lib_name() == "WT4AWeccCurrentSource")
    for wecc in weccs:
        value = wecc.parset.get_param_value("WT4A_PMaxPu")
        wecc.parset.remove_param_or_ref("WT4A_PMaxPu")
        wecc.parset.add_param("DOUBLE", "WT4A_PMaxREECPu", value)
        value = wecc.parset.get_param_value("WT4A_PMinPu")
        wecc.parset.remove_param_or_ref("WT4A_PMinPu")
        wecc.parset.add_param("DOUBLE", "WT4A_PMinREECPu", value)
        value = wecc.parset.get_param_value("WT4A_QMaxPu")
        wecc.parset.remove_param_or_ref("WT4A_QMaxPu")
        wecc.parset.add_param("DOUBLE", "WT4A_QMaxREECPu", value)
        value = wecc.parset.get_param_value("WT4A_QMinPu")
        wecc.parset.remove_param_or_ref("WT4A_QMinPu")
        wecc.parset.add_param("DOUBLE", "WT4A_QMinREECPu", value)
        value = wecc.parset.get_param_value("WT4A_tP")
        wecc.parset.remove_param_or_ref("WT4A_tP")
        wecc.parset.add_param("DOUBLE", "WT4A_tpREEC", value)
        value = wecc.parset.get_param_value("WT4A_tp")
        wecc.parset.remove_param_or_ref("WT4A_tp")
        wecc.parset.add_param("DOUBLE", "WT4A_tpWTGTb", value)
