within Dynawo.Electrical.Sources;



model AcGrid "AC Grid from IEE explorer paper from Carmen C."

//  final parameter Real K_FH = 1 + FH;
  parameter Real SNom =SystemBase.SnRef;
  parameter Real U0pu;
  parameter Real UPhase0;
  parameter Real Upu(start=U0pu)  ;
  parameter Real UPhase(start=UPhase0) ;
  parameter Real omegaRefPu=SystemBase.omegaRef0Pu;


  parameter Real R = 0.05 "Governor Droop";
  parameter Real FH = 0.3 "Fraction of the total power generated by the HP turbine";
  parameter Real H = 4 "Inertie constant";
  parameter Real TR = 8 "Reheat time constant, seconds";
  parameter Real Km = 0.95 "Mechanical power gain factor";
  parameter Real D = 1 "Damping Factor";


  Modelica.Blocks.Continuous.FirstOrder firstOrder(T = TR, k = 1 - FH) annotation(
    Placement(visible = true, transformation(origin = {-38, 24}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Gain FH_(k = FH) annotation(
    Placement(visible = true, transformation(origin = {-36, 68}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Add add annotation(
    Placement(visible = true, transformation(origin = {10, 52}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Add add1(k2 = -1) annotation(
    Placement(visible = true, transformation(origin = {-104, 68}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Gain gain(k = 1 / R) annotation(
    Placement(visible = true, transformation(origin = {-27, -35}, extent = {{15, -15}, {-15, 15}}, rotation = 0)));
  Modelica.Blocks.Continuous.Integrator integrator(k = 1 / (2 * H)) annotation(
    Placement(visible = true, transformation(origin = {162, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Gain gain1(k = Km) annotation(
    Placement(visible = true, transformation(origin = {52, 52}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Gain gain2(k = D) annotation(
    Placement(visible = true, transformation(origin = {138, 8}, extent = {{10, -10}, {-10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Add3 add3(k2 = -1, k3 = -1) annotation(
    Placement(visible = true, transformation(origin = {106, 50}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Continuous.Integrator integrator1(k = SystemBase.omegaNom, y_start = 0) annotation(
    Placement(visible = true, transformation(origin = {458, -42}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step Psetpoint(height = 0, offset = 1)  annotation(
    Placement(visible = true, transformation(origin = {-176, 114}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Add add2 annotation(
    Placement(visible = true, transformation(origin = {300, 44}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Add add4(k2 = -1)  annotation(
    Placement(visible = true, transformation(origin = {402, -44}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Dynawo.Electrical.Sources.PhaseurGrid phaseurGrid(SNom = SNom, UPhase = UPhase, UPhase0 = UPhase0, UPu = Upu, U0Pu = U0pu) annotation(
    Placement(visible = true, transformation(origin = {540, -28}, extent = {{-30, -30}, {30, 30}}, rotation = 0)));
  Dynawo.Connectors.ACPower aCPower annotation(
    Placement(visible = true, transformation(origin = {689, -23}, extent = {{-23, -23}, {23, 23}}, rotation = 0), iconTransformation(origin = {120, 74}, extent = {{-20, -20}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Interfaces.RealOutput omegaPu annotation(
    Placement(visible = true, transformation(origin = {538, 56}, extent = {{-15, -15}, {15, 15}}, rotation = 0), iconTransformation(extent = {{99, -73}, {129, -43}}, rotation = 0)));
  Modelica.Blocks.Math.Gain gain3(k = 1) annotation(
    Placement(visible = true, transformation(origin = {133, -35}, extent = {{15, -15}, {-15, 15}}, rotation = 0)));
  Modelica.Blocks.Continuous.Integrator integrator3(k = 1, y_start = 0) annotation(
    Placement(visible = true, transformation(origin = {286, 228}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step RoCof(height = -0.01, offset = 0, startTime = 15) annotation(
    Placement(visible = true, transformation(origin = {180, 282}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Add add5 annotation(
    Placement(visible = true, transformation(origin = {366, 90}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Logical.Switch switch1 annotation(
    Placement(visible = true, transformation(origin = {238, 104}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Constant Wrotor_t0(k = 0)  annotation(
    Placement(visible = true, transformation(origin = {161, 131}, extent = {{-19, -19}, {19, 19}}, rotation = 0)));
  Modelica.Blocks.Sources.BooleanStep ActivateOmegaConstante(startTime = 0)  annotation(
    Placement(visible = true, transformation(origin = {107, 103}, extent = {{-13, -13}, {13, 13}}, rotation = 0)));
  Modelica.Blocks.Math.Add add6 annotation(
    Placement(visible = true, transformation(origin = {226, 254}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step step(height = 0.01, offset = 0, startTime = 18) annotation(
    Placement(visible = true, transformation(origin = {180, 246}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Interfaces.RealInput OmegaRef annotation(
    Placement(visible = true, transformation(origin = {240, -16}, extent = {{-20, -20}, {20, 20}}, rotation = 0), iconTransformation(origin = {-120, 52}, extent = {{-20, -20}, {20, 20}}, rotation = 0)));
  Modelica.Blocks.Math.Add add7 annotation(
    Placement(visible = true, transformation(origin = {418, 92}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Continuous.Integrator integrator2(k = 1, y_start = 0) annotation(
    Placement(visible = true, transformation(origin = {438, 198}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step step1(height = +0.01, offset = 0, startTime = 25) annotation(
    Placement(visible = true, transformation(origin = {332, 252}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step step2(height = -0.01, offset = 0, startTime = 28) annotation(
    Placement(visible = true, transformation(origin = {332, 216}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Add add8 annotation(
    Placement(visible = true, transformation(origin = {378, 224}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
  connect(firstOrder.y, add.u2) annotation(
    Line(points = {{-26, 24}, {-14, 24}, {-14, 46}, {-2, 46}}, color = {0, 0, 127}));
  connect(add1.y, FH_.u) annotation(
    Line(points = {{-92, 68}, {-48, 68}}, color = {0, 0, 127}));
  connect(firstOrder.u, add1.y) annotation(
    Line(points = {{-50, 24}, {-80, 24}, {-80, 58}, {-92, 58}, {-92, 68}}, color = {0, 0, 127}));
  connect(add.y, gain1.u) annotation(
    Line(points = {{22, 52}, {40, 52}}, color = {0, 0, 127}));
  connect(gain1.y, add3.u1) annotation(
    Line(points = {{64, 52}, {72, 52}, {72, 58}, {94, 58}}, color = {0, 0, 127}));
  connect(add3.y, integrator.u) annotation(
    Line(points = {{118, 50}, {150, 50}}, color = {0, 0, 127}));
  connect(gain2.y, add3.u3) annotation(
    Line(points = {{128, 8}, {82, 8}, {82, 42}, {94, 42}}, color = {0, 0, 127}));
  connect(gain2.u, integrator.y) annotation(
    Line(points = {{150, 8}, {192, 8}, {192, 50}, {174, 50}}, color = {0, 0, 127}));
  connect(add1.y, FH_.u) annotation(
    Line(points = {{-92, 68}, {-48, 68}}, color = {0, 0, 127}));
  connect(gain.y, add1.u2) annotation(
    Line(points = {{-43.5, -35}, {-156, -35}, {-156, 62}, {-116, 62}}, color = {0, 0, 127}));
  connect(FH_.y, add.u1) annotation(
    Line(points = {{-24, 68}, {-18, 68}, {-18, 58}, {-2, 58}}, color = {0, 0, 127}));
  connect(Psetpoint.y, add1.u1) annotation(
    Line(points = {{-165, 114}, {-144.5, 114}, {-144.5, 74}, {-116, 74}}, color = {0, 0, 127}));
  connect(add4.y, integrator1.u) annotation(
    Line(points = {{413, -44}, {430, -44}, {430, -42}, {445, -42}}, color = {0, 0, 127}));
  connect(phaseurGrid.PPu, add3.u2) annotation(
    Line(points = {{573, -14}, {634, -14}, {634, -78}, {76, -78}, {76, 50}, {94, 50}}, color = {0, 0, 127}));
  connect(gain.u, gain3.y) annotation(
    Line(points = {{-8, -34}, {116.5, -34}, {116.5, -35}}, color = {0, 0, 127}));
  connect(gain3.u, integrator.y) annotation(
    Line(points = {{151, -35}, {174, -35}, {174, 50}}, color = {0, 0, 127}));
  connect(integrator1.y, phaseurGrid.UPhaseOffs) annotation(
    Line(points = {{469, -42}, {504, -42}}, color = {0, 0, 127}));
  connect(add5.u2, add2.y) annotation(
    Line(points = {{354, 84}, {314, 84}, {314, 44}, {311, 44}}, color = {0, 0, 127}));
  connect(integrator3.y, add5.u1) annotation(
    Line(points = {{297, 228}, {311.5, 228}, {311.5, 96}, {354, 96}}, color = {0, 0, 127}));
  connect(add4.u1, omegaPu) annotation(
    Line(points = {{390, -38}, {380, -38}, {380, 56}, {538, 56}}, color = {0, 0, 127}));
  connect(phaseurGrid.terminal, aCPower) annotation(
    Line(points = {{572, -26}, {690, -26}, {690, -22}}, color = {0, 0, 255}));
  connect(integrator.y, switch1.u3) annotation(
    Line(points = {{174, 50}, {216, 50}, {216, 96}, {226, 96}}, color = {0, 0, 127}));
  connect(switch1.y, add2.u1) annotation(
    Line(points = {{250, 104}, {276, 104}, {276, 50}, {288, 50}}, color = {0, 0, 127}));
  connect(Wrotor_t0.y, switch1.u1) annotation(
    Line(points = {{182, 131}, {182, 112}, {226, 112}}, color = {0, 0, 127}));
  connect(ActivateOmegaConstante.y, switch1.u2) annotation(
    Line(points = {{121, 103}, {192, 103}, {192, 104}, {226, 104}}, color = {255, 0, 255}));
  connect(RoCof.y, add6.u1) annotation(
    Line(points = {{191, 282}, {202.5, 282}, {202.5, 260}, {214, 260}}, color = {0, 0, 127}));
  connect(add6.y, integrator3.u) annotation(
    Line(points = {{237, 254}, {255, 254}, {255, 228}, {273, 228}}, color = {0, 0, 127}));
  connect(step.y, add6.u2) annotation(
    Line(points = {{191, 246}, {213, 246}, {213, 248}}, color = {0, 0, 127}));
  connect(OmegaRef, add4.u2) annotation(
    Line(points = {{240, -16}, {322, -16}, {322, -50}, {390, -50}}, color = {0, 0, 127}));
  connect(OmegaRef, add2.u2) annotation(
    Line(points = {{240, -16}, {274, -16}, {274, 38}, {288, 38}}, color = {0, 0, 127}));
  connect(add5.y, add7.u2) annotation(
    Line(points = {{378, 90}, {406, 90}, {406, 86}}, color = {0, 0, 127}));
  connect(add7.y, omegaPu) annotation(
    Line(points = {{430, 92}, {538, 92}, {538, 56}}, color = {0, 0, 127}));
  connect(step2.y, add8.u2) annotation(
    Line(points = {{343, 216}, {365, 216}, {365, 218}}, color = {0, 0, 127}));
  connect(add8.y, integrator2.u) annotation(
    Line(points = {{389, 224}, {407, 224}, {407, 198}, {425, 198}}, color = {0, 0, 127}));
  connect(step1.y, add8.u1) annotation(
    Line(points = {{343, 252}, {354.5, 252}, {354.5, 230}, {366, 230}}, color = {0, 0, 127}));
  connect(integrator2.y, add7.u1) annotation(
    Line(points = {{450, 198}, {480, 198}, {480, 162}, {390, 162}, {390, 98}, {406, 98}}, color = {0, 0, 127}));
  annotation(
    Diagram(coordinateSystem(extent = {{-200, 300}, {720, -80}}), graphics = {Text(origin = {5, 241}, extent = {{-139, 9}, {139, -9}}, textString = "add a disturbance to omega to emulate a RoCof"), Text(origin = {82, 63}, extent = {{-14, 5}, {14, -5}}, textString = "Pm"), Text(origin = {82, 55}, extent = {{-14, 5}, {14, -5}}, textString = "Pe"), Text(origin = {145, 72}, extent = {{-21, 12}, {21, -12}}, textString = "1/(2H+s)"), Text(origin = {-150, 121}, extent = {{-14, 5}, {14, -5}}, textString = "Pref"), Text(origin = {-144, 69}, extent = {{-14, 5}, {14, -5}}, textString = "PRF"), Text(origin = {211, 57}, extent = {{-15, 9}, {15, -9}}, textString = "Wrotor-W0"), Rectangle(origin = {153, 36}, extent = {{-35, 46}, {35, -46}}), Text(origin = {309, 75}, extent = {{-25, 9}, {25, -9}}, textString = "Wrotor"), Text(origin = {-3, 156}, extent = {{-121, 66}, {121, -66}}, textString = "not consider inertia of AC GRID if ACTIVATE is TRUE"), Text(origin = {72, 204}, extent = {{-72, 16}, {72, -16}}, textString = "offset StartTime")}),
    experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-06, Interval = 0.002),
  Icon(coordinateSystem(extent = {{-100, -100}, {100, 100}}), graphics = {Text(origin = {175, -38}, extent = {{-45, 40}, {45, -40}}, textString = "OmegaPu"), Rectangle(extent = {{-100, 100}, {100, -100}}), Text(origin = {2, 8}, extent = {{-74, 50}, {74, -50}}, textString = "ACGrid")}));
end AcGrid;
