within Dynawo.Electrical.Controls.Frequency.SystemFrequencyResponse;

/*
* Copyright (c) 2024, RTE (http://www.rte-france.com)
* See AUTHORS.txt
* All rights reserved.
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, you can obtain one at http://mozilla.org/MPL/2.0/.
* SPDX-License-Identifier: MPL-2.0
*
* This file is part of Dynawo, an hybrid C++/Modelica open source suite of simulation tools for power systems.
*/

record SFRParameters

  parameter Types.PerUnit DPu "Damping coefficient of the swing equation in pu (base SNom/omegaNom)";
  parameter Real Fh "Fraction of the total power generated by the high pressure turbine (0...1)";
  parameter Types.Time H "Inertia constant in s";
  parameter Real Km "Mechanical power gain factor";
  parameter Types.PerUnit R "Governor droop in pu (base omegaNom/SNom)";
  parameter Types.Time Tr "Reheat time constant in s";

  annotation(preferredView = "text");
end SFRParameters;
