within Dynawo.Electrical.EMT;

/*
* Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
* See AUTHORS.txt
* All rights reserved.
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, you can obtain one at http://mozilla.org/MPL/2.0/.
* SPDX-License-Identifier: MPL-2.0
*
* This file is part of Dynawo, an hybrid C++/Modelica open source time domain simulation tool for power systems.
*
* Recovered from the EMTSim grid-forming/grid-feeding converter case
* (EMTSim.Examples.IEEE5bus_gridfeeding) via the OMC instantiated-model dump in the
* original IDASPM zip's dynamoCompiler.log. Flat (fully instantiated) form:
* parameters are baked to the original operating point.
*/

model IEEE5bus_gridfeeding
  Real IEEE5bus_gridfeeding_Bus2_p_v[3](start = {IEEE5bus_gridfeeding_Bus2_V0[1], IEEE5bus_gridfeeding_Bus2_V0[2], IEEE5bus_gridfeeding_Bus2_V0[3]});
  Real IEEE5bus_gridfeeding_Bus2_p_i[3];
  parameter Real IEEE5bus_gridfeeding_Bus2_V_0 = 1.0 "Voltage magnitude (pu/SI)";
  parameter Real IEEE5bus_gridfeeding_Bus2_angle_0 = 0.0 "Voltage angle (deg)";
  parameter Real IEEE5bus_gridfeeding_Bus2_angle_0_rad(quantity = "Angle", unit = "rad", displayUnit = "deg") = 0.0174532925199433 * IEEE5bus_gridfeeding_Bus2_angle_0 "Voltage angle (radian)";
  parameter Real IEEE5bus_gridfeeding_Bus2_V0[3] = {cos(IEEE5bus_gridfeeding_Bus2_angle_0_rad) * 0.816496580927726 * IEEE5bus_gridfeeding_Bus2_V_0, cos(-2.094395102393195 + IEEE5bus_gridfeeding_Bus2_angle_0_rad) * 0.816496580927726 * IEEE5bus_gridfeeding_Bus2_V_0, cos(2.094395102393195 + IEEE5bus_gridfeeding_Bus2_angle_0_rad) * 0.816496580927726 * IEEE5bus_gridfeeding_Bus2_V_0};
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Un(quantity = "ElectricPotential", unit = "V") = 100000.0 "Nominal voltage";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_cos_phin = 0.9;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_fn(quantity = "Frequency", unit = "Hz") = 50.0;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Pn(quantity = "Power", unit = "W") = 4000000000.0 "Nominal apparent power (or Pn and cos_phin)";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Sn(quantity = "Power", unit = "VA") = IEEE5bus_gridfeeding_GridFeeding2_Pn / IEEE5bus_gridfeeding_GridFeeding2_cos_phin;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Lf_pu = 0.6;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Rf_pu = 0.0001221;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Lf_SI(quantity = "Inductance", unit = "H") = IEEE5bus_gridfeeding_GridFeeding2_Lf_pu * IEEE5bus_gridfeeding_GridFeeding2_Zb / IEEE5bus_gridfeeding_GridFeeding2_wb;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Rf_SI(quantity = "Resistance", unit = "Ohm") = IEEE5bus_gridfeeding_GridFeeding2_Rf_pu * IEEE5bus_gridfeeding_GridFeeding2_Zb;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Pref0 = -44444444.44444444 "initial active power reference in SI";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Qref0 = 33333333.33333333 "initial reactive power reference in SI";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Pref0_pu = IEEE5bus_gridfeeding_GridFeeding2_Pref0 / IEEE5bus_gridfeeding_GridFeeding2_Sn;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Qref0_pu = IEEE5bus_gridfeeding_GridFeeding2_Qref0 / IEEE5bus_gridfeeding_GridFeeding2_Sn;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_V0(quantity = "ElectricPotential", unit = "V") = 103670.0 "Initial voltage in RMS Line-Line at the connexion point of converter";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_wb(quantity = "AngularVelocity", unit = "rad/s") = 6.283185307179586 * IEEE5bus_gridfeeding_GridFeeding2_fn;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Tr_i = 0.01;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_zeta_i = 0.7;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_wn_i = 3.0 / IEEE5bus_gridfeeding_GridFeeding2_Tr_i;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Ti_i = 2.0 * IEEE5bus_gridfeeding_GridFeeding2_zeta_i / IEEE5bus_gridfeeding_GridFeeding2_wn_i - IEEE5bus_gridfeeding_GridFeeding2_Rf_pu * (1.0 / IEEE5bus_gridfeeding_GridFeeding2_wn_i / IEEE5bus_gridfeeding_GridFeeding2_wn_i) * IEEE5bus_gridfeeding_GridFeeding2_wb / IEEE5bus_gridfeeding_GridFeeding2_Lf_pu;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Kp_i = 2.0 * IEEE5bus_gridfeeding_GridFeeding2_zeta_i * IEEE5bus_gridfeeding_GridFeeding2_wn_i * IEEE5bus_gridfeeding_GridFeeding2_Lf_pu / IEEE5bus_gridfeeding_GridFeeding2_wb - IEEE5bus_gridfeeding_GridFeeding2_Rf_pu;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Ki_i = IEEE5bus_gridfeeding_GridFeeding2_Kp_i / IEEE5bus_gridfeeding_GridFeeding2_Ti_i;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_vgd0 = IEEE5bus_gridfeeding_GridFeeding2_V0 / IEEE5bus_gridfeeding_GridFeeding2_Vb;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_vgq0 = 0.0;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_isdref = if (-IEEE5bus_gridfeeding_GridFeeding2_Pref0_pu) / IEEE5bus_gridfeeding_GridFeeding2_vgd0 > 1.0 then 1.0 else if (-IEEE5bus_gridfeeding_GridFeeding2_Pref0_pu) / IEEE5bus_gridfeeding_GridFeeding2_vgd0 < -1.0 then -1.0 else (-IEEE5bus_gridfeeding_GridFeeding2_Pref0_pu) / IEEE5bus_gridfeeding_GridFeeding2_vgd0;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_isqref = if IEEE5bus_gridfeeding_GridFeeding2_Qref0_pu / IEEE5bus_gridfeeding_GridFeeding2_vgd0 > 1.0 then 1.0 else if IEEE5bus_gridfeeding_GridFeeding2_Qref0_pu / IEEE5bus_gridfeeding_GridFeeding2_vgd0 < -1.0 then -1.0 else IEEE5bus_gridfeeding_GridFeeding2_Qref0_pu / IEEE5bus_gridfeeding_GridFeeding2_vgd0;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Ub(quantity = "ElectricPotential", unit = "V") = IEEE5bus_gridfeeding_GridFeeding2_Un;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Vb(quantity = "ElectricPotential", unit = "V") = IEEE5bus_gridfeeding_GridFeeding2_Ub;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Ib(quantity = "ElectricCurrent", unit = "A") = 1.732050807568877 * IEEE5bus_gridfeeding_GridFeeding2_Sn / (1.732050807568877 * IEEE5bus_gridfeeding_GridFeeding2_Ub);
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Zb(quantity = "Resistance", unit = "Ohm") = IEEE5bus_gridfeeding_GridFeeding2_Vb / IEEE5bus_gridfeeding_GridFeeding2_Ib;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_wn_pll(quantity = "AngularVelocity", unit = "rad/s") = 314.1592653589793;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_zeta_pll = 0.7;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Kp_pll = 2.0 * IEEE5bus_gridfeeding_GridFeeding2_zeta_pll * IEEE5bus_gridfeeding_GridFeeding2_wn_pll / IEEE5bus_gridfeeding_GridFeeding2_Ub;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Ti_pll = 2.0 * IEEE5bus_gridfeeding_GridFeeding2_zeta_pll / IEEE5bus_gridfeeding_GridFeeding2_wn_pll;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_init_w(quantity = "AngularVelocity", unit = "rad/s") = 6.283185307179586 * IEEE5bus_gridfeeding_GridFeeding2_fn;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_init_theta = -2.64 "in degree";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad(quantity = "Angle", unit = "rad", displayUnit = "deg") = 0.0174532925199433 * IEEE5bus_gridfeeding_GridFeeding2_init_theta "in radian";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_isd0 = IEEE5bus_gridfeeding_GridFeeding2_isdref;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_isq0 = IEEE5bus_gridfeeding_GridFeeding2_isqref;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Vg0[3] = {IEEE5bus_gridfeeding_GridFeeding2_V0 * cos(IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * 0.816496580927726, IEEE5bus_gridfeeding_GridFeeding2_V0 * cos(-2.094395102393195 + IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * 0.816496580927726, IEEE5bus_gridfeeding_GridFeeding2_V0 * cos(2.094395102393195 + IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * 0.816496580927726};
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Is0[3] = {0.816496580927726 * (cos(IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * IEEE5bus_gridfeeding_GridFeeding2_isd0 - sin(IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * IEEE5bus_gridfeeding_GridFeeding2_isq0) * IEEE5bus_gridfeeding_GridFeeding2_Ib, 0.816496580927726 * (cos(-2.094395102393195 + IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * IEEE5bus_gridfeeding_GridFeeding2_isd0 - sin(-2.094395102393195 + IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * IEEE5bus_gridfeeding_GridFeeding2_isq0) * IEEE5bus_gridfeeding_GridFeeding2_Ib, 0.816496580927726 * (cos(2.094395102393195 + IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * IEEE5bus_gridfeeding_GridFeeding2_isd0 - sin(2.094395102393195 + IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad) * IEEE5bus_gridfeeding_GridFeeding2_isq0) * IEEE5bus_gridfeeding_GridFeeding2_Ib};
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Vs(quantity = "ElectricPotential", unit = "V") = IEEE5bus_gridfeeding_GridFeeding2_Vs;
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_fg[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_p_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v1(unit = "V") "Voltage between pin p and n as input signal for phase a";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v2(unit = "V") "Voltage between pin p and n as input signal for phase b";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v3(unit = "V") "Voltage between pin p and n as input signal for phase c";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_uMax(start = 1.0) = 1.0 "Upper limits of input signals";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_uMin = -IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_uMax "Lower limits of input signals";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_strict = false "= true, if strict limits with noEvent(..)";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_limitsAtInit = true "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator)";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_uMax(start = 1.0) = 1.0 "Upper limits of input signals";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_uMin = -IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_uMax "Lower limits of input signals";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_strict = false "= true, if strict limits with noEvent(..)";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_limitsAtInit = true "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator)";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_uMax(start = 1.0) = 1.0 "Upper limits of input signals";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_uMin = -IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_uMax "Lower limits of input signals";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_strict = false "= true, if strict limits with noEvent(..)";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_limitsAtInit = true "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator)";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Vb(quantity = "ElectricPotential", unit = "V") = IEEE5bus_gridfeeding_GridFeeding2_Vb;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Ib(quantity = "ElectricCurrent", unit = "A") = IEEE5bus_gridfeeding_GridFeeding2_Ib;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg0[3] = {IEEE5bus_gridfeeding_GridFeeding2_Vg0[1], IEEE5bus_gridfeeding_GridFeeding2_Vg0[2], IEEE5bus_gridfeeding_GridFeeding2_Vg0[3]};
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Is0[3] = {IEEE5bus_gridfeeding_GridFeeding2_Is0[1], IEEE5bus_gridfeeding_GridFeeding2_Is0[2], IEEE5bus_gridfeeding_GridFeeding2_Is0[3]};
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_isd0 = IEEE5bus_gridfeeding_GridFeeding2_isd0;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_isq0 = IEEE5bus_gridfeeding_GridFeeding2_isq0;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Kp_pll = IEEE5bus_gridfeeding_GridFeeding2_Kp_pll;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Ti_pll = IEEE5bus_gridfeeding_GridFeeding2_Ti_pll;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_init_w(quantity = "AngularVelocity", unit = "rad/s") = IEEE5bus_gridfeeding_GridFeeding2_init_w;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_init_theta(quantity = "Angle", unit = "rad", displayUnit = "deg") = IEEE5bus_gridfeeding_GridFeeding2_init_theta_rad;
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Is[3](start = {IEEE5bus_gridfeeding_GridFeeding2_PLL_Is0[1], IEEE5bus_gridfeeding_GridFeeding2_PLL_Is0[2], IEEE5bus_gridfeeding_GridFeeding2_PLL_Is0[3]});
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[3](start = {IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg0[1], IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg0[2], IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg0[3]}, each fixed = true);
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Theta(quantity = "Angle", unit = "rad", displayUnit = "rad", start = IEEE5bus_gridfeeding_GridFeeding2_PLL_init_theta);
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Ws(quantity = "AngularVelocity", unit = "rad/s", start = IEEE5bus_gridfeeding_GridFeeding2_PLL_init_w, fixed = true);
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_isd(start = IEEE5bus_gridfeeding_GridFeeding2_PLL_isd0) "AC side grid Current axis d in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_isq(start = IEEE5bus_gridfeeding_GridFeeding2_PLL_isq0) "AC side grid Current axis q in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_vgd;
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_vgq;
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_dq0[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_theta(quantity = "Angle", unit = "rad", displayUnit = "rad") "angle between axis a and axis ir";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[3];
  final constant Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_concordia_matrix[3,3] = {{0.816496580927726, -0.408248290463863, -0.408248290463863}, {0.0, 0.7071067811865475, -0.7071067811865475}, {0.5773502691896257, 0.5773502691896257, 0.5773502691896257}};
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[3,3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_dq0[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_theta(quantity = "Angle", unit = "rad", displayUnit = "rad") "angle between axis a and axis ir";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[3];
  final constant Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_concordia_matrix[3,3] = {{0.816496580927726, -0.408248290463863, -0.408248290463863}, {0.0, 0.7071067811865475, -0.7071067811865475}, {0.5773502691896257, 0.5773502691896257, 0.5773502691896257}};
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[3,3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_dq0[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_theta(quantity = "Angle", unit = "rad", displayUnit = "rad") "angle between axis a and axis ir";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[3];
  final constant Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_concordia_matrix[3,3] = {{0.816496580927726, -0.408248290463863, -0.408248290463863}, {0.0, 0.7071067811865475, -0.7071067811865475}, {0.5773502691896257, 0.5773502691896257, 0.5773502691896257}};
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[3,3];
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_k(unit = "1") = IEEE5bus_gridfeeding_GridFeeding2_PLL_Kp_pll "Gain";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_T(quantity = "Time", unit = "s", min = 1e-60, start = 1.0) = IEEE5bus_gridfeeding_GridFeeding2_PLL_Ti_pll "Time Constant (T>0 required)";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_x_start = 0.0 "Initial or guess value of state";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_y_start = IEEE5bus_gridfeeding_GridFeeding2_PLL_init_w "Initial value of output";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_x(start = IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_x_start) "State of block";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y(start = IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y_start) "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_k(unit = "1") = 1.0 "Integrator gain";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y_start = IEEE5bus_gridfeeding_GridFeeding2_PLL_init_theta "Initial or guess value of output (= state)";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Sn(quantity = "Power", unit = "VA") = IEEE5bus_gridfeeding_GridFeeding2_Sn "Converter nominal power";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Vd_grid "pu value";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Pref "SI value (convention recepteur)";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Qref "SI value (convention recepteur)";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_isd_ref "pu value";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_isq_ref "pu value";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_uMax(start = 1.0) = 1.0 "Upper limits of input signals";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_uMin = -IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_uMax "Lower limits of input signals";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_strict = false "= true, if strict limits with noEvent(..)";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_limitsAtInit = true "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator)";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_uMax(start = 1.0) = 1.0 "Upper limits of input signals";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_uMin = -IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_uMax "Lower limits of input signals";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_strict = false "= true, if strict limits with noEvent(..)";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_limitsAtInit = true "Has no longer an effect and is only kept for backwards compatibility (the implementation uses now the homotopy operator)";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vb(quantity = "ElectricPotential", unit = "V") = IEEE5bus_gridfeeding_GridFeeding2_Un;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Lf_pu = IEEE5bus_gridfeeding_GridFeeding2_Lf_pu;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_wb(quantity = "AngularVelocity", unit = "rad/s") = IEEE5bus_gridfeeding_GridFeeding2_wb;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ti_i = IEEE5bus_gridfeeding_GridFeeding2_Ti_i;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Kp_i = IEEE5bus_gridfeeding_GridFeeding2_Kp_i;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isdref = IEEE5bus_gridfeeding_GridFeeding2_isdref;
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isqref = IEEE5bus_gridfeeding_GridFeeding2_isqref;
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_vgd "AC side grid voltage axis d in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_vgq "AC side grid voltage axis q in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isd "AC side grid Current axis d in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isq "AC side grid Current axis q in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isd_ref "AC side grid Current reference value axis d in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isq_ref "AC side grid Current reference value axis q in pu";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vs(quantity = "ElectricPotential", unit = "V") "DC bus voltage";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ws(quantity = "AngularVelocity", unit = "rad/s") "Grid angular velocity mesured";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Theta(quantity = "Angle", unit = "rad", displayUnit = "deg") "Angle for Park transform";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fg[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vd_ref;
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vq_ref;
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_y(start = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_y_start) "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_k(unit = "1") = 1.0 "Gain";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_T(quantity = "Time", unit = "s", start = 1.0) = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ti_i "Time Constant";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_y_start = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isdref "Initial or guess value of output (= state)";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_k(unit = "1") = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Kp_i "Gain";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_T(quantity = "Time", unit = "s", min = 1e-60, start = 1.0) = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ti_i "Time Constant (T>0 required)";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_x_start = 0.0 "Initial or guess value of state";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_y_start = 0.0 "Initial value of output";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_x(start = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_x_start) "State of block";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_y(start = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_y_start) "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_k(unit = "1") = 1.0 "Gain";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_T(quantity = "Time", unit = "s", start = 1.0) = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ti_i "Time Constant";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_y_start = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isqref "Initial or guess value of output (= state)";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_u "Connector of Real input signal";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_k(unit = "1") = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Kp_i "Gain";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_T(quantity = "Time", unit = "s", min = 1e-60, start = 1.0) = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ti_i "Time Constant (T>0 required)";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_x_start = 0.0 "Initial or guess value of state";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_y_start = 0.0 "Initial value of output";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_x(start = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_x_start) "State of block";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_dq0[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_theta(quantity = "Angle", unit = "rad", displayUnit = "rad") "angle between axis a and axis ir";
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[3];
  final constant Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_concordia_matrix[3,3] = {{0.816496580927726, -0.408248290463863, -0.408248290463863}, {0.0, 0.7071067811865475, -0.7071067811865475}, {0.5773502691896257, 0.5773502691896257, 0.5773502691896257}};
  Real IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[3,3];
  Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[3];
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_X(quantity = "Resistance", unit = "Ohm") = 0.1 "inductance of the RL circuit, default value 0.1 ";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_L(quantity = "Inductance", unit = "H") = IEEE5bus_gridfeeding_GridFeeding2_Lf_SI "inductance of the RL circuit";
  parameter Real IEEE5bus_gridfeeding_GridFeeding2_RL_converter_R(quantity = "Resistance", unit = "Ohm") = IEEE5bus_gridfeeding_GridFeeding2_Rf_SI "resistance of the RL circuit";
  parameter Boolean IEEE5bus_gridfeeding_GridFeeding2_RL_converter_pu = false "use of per unit value for the model true/false";
  Real IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_I[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_V[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Ground_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Ground_p_i[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_Pref(start = IEEE5bus_gridfeeding_GridFeeding2_Pref0, fixed = true) "Active power reference in SI";
  Real IEEE5bus_gridfeeding_GridFeeding2_Qref(start = IEEE5bus_gridfeeding_GridFeeding2_Qref0, fixed = true) "Reactive power reference in SI";
  Real IEEE5bus_gridfeeding_GridFeeding2_Vs "DC bus voltage";
  Real IEEE5bus_gridfeeding_GridFeeding2_p_v[3];
  Real IEEE5bus_gridfeeding_GridFeeding2_p_i[3];
  Real IEEE5bus_gridfeeding_cst2_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_cst2_k(start = 1.0) = 207340.0 "Constant output value";
  Real IEEE5bus_gridfeeding_StepPrefE1_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_StepPrefE1_offset = 0.0 "Offset of output signal y";
  parameter Real IEEE5bus_gridfeeding_StepPrefE1_startTime(quantity = "Time", unit = "s") = 6.0 "Output y = offset for time < startTime";
  parameter Real IEEE5bus_gridfeeding_StepPrefE1_height = -11111111.11111111 "Height of step";
  Real IEEE5bus_gridfeeding_StepPrefE2_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_StepPrefE2_offset = 0.0 "Offset of output signal y";
  parameter Real IEEE5bus_gridfeeding_StepPrefE2_startTime(quantity = "Time", unit = "s") = 6.5 "Output y = offset for time < startTime";
  parameter Real IEEE5bus_gridfeeding_StepPrefE2_height = 11111111.11111111 "Height of step";
  Real IEEE5bus_gridfeeding_StepQrefE1_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_StepQrefE1_offset = 0.0 "Offset of output signal y";
  parameter Real IEEE5bus_gridfeeding_StepQrefE1_startTime(quantity = "Time", unit = "s") = 6.0 "Output y = offset for time < startTime";
  parameter Real IEEE5bus_gridfeeding_StepQrefE1_height = 5555555.555555555 "Height of step";
  Real IEEE5bus_gridfeeding_StepQrefE2_y "Connector of Real output signal";
  parameter Real IEEE5bus_gridfeeding_StepQrefE2_offset = 0.0 "Offset of output signal y";
  parameter Real IEEE5bus_gridfeeding_StepQrefE2_startTime(quantity = "Time", unit = "s") = 6.5 "Output y = offset for time < startTime";
  parameter Real IEEE5bus_gridfeeding_StepQrefE2_height = -5555555.555555555 "Height of step";
initial equation
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y = IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y_start;
equation
  IEEE5bus_gridfeeding_Bus2_p_i[1] = 0.0;
  IEEE5bus_gridfeeding_Bus2_p_i[2] = 0.0;
  IEEE5bus_gridfeeding_Bus2_p_i[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_fg = {IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fg[1], IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fg[2], IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fg[3]};
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[1] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v1;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[2] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v2;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[3] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v3;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[1] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_v[1] - IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[2] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_v[2] - IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[3] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_v[3] - IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_v[3];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[1] + IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_i[1];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[2] + IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_i[2];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[3] + IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_i[1] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[1];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_i[2] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[2];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_i[3] = IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_v[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_v[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_v[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_y = homotopy(smooth(0, if IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_u > IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_uMax then IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_uMax else if IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_u < IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_uMin then IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_uMin else IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_u), IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_u);
  IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_y = homotopy(smooth(0, if IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_u > IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_uMax then IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_uMax else if IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_u < IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_uMin then IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_uMin else IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_u), IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_u);
  IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_y = homotopy(smooth(0, if IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_u > IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_uMax then IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_uMax else if IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_u < IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_uMin then IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_uMin else IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_u), IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_u);
  IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_u = IEEE5bus_gridfeeding_GridFeeding2_Conv_fg[1];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_u = IEEE5bus_gridfeeding_GridFeeding2_Conv_fg[2];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_u = IEEE5bus_gridfeeding_GridFeeding2_Conv_fg[3];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[1] = 0.5 * IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_a_y * IEEE5bus_gridfeeding_GridFeeding2_Conv_Vs;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[2] = 0.5 * IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_b_y * IEEE5bus_gridfeeding_GridFeeding2_Conv_Vs;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_v[3] = 0.5 * IEEE5bus_gridfeeding_GridFeeding2_Conv_Lim_c_y * IEEE5bus_gridfeeding_GridFeeding2_Conv_Vs;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[1] = 0.816496580927726 * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[1] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[2] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[2] = 0.7071067811865475 * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[2] + (-0.7071067811865475) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[3] = 0.5773502691896257 * (IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[3]);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[1,1] = cos(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[1,2] = sin(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[1,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[2,1] = -sin(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[2,2] = cos(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[2,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[3,1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[3,2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[3,3] = 1.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_abc[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[1];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_abc[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[2];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_abc[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_dq0[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[1,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[1,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[1,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_dq0[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[2,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[2,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[2,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_dq0[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[3,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[3,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_rotation_matrix[3,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[1] = 0.816496580927726 * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[1] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[2] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[2] = 0.7071067811865475 * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[2] + (-0.7071067811865475) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[3] = 0.5773502691896257 * (IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[3]);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[1,1] = cos(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[1,2] = sin(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[1,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[2,1] = -sin(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[2,2] = cos(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[2,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[3,1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[3,2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[3,3] = 1.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_abc[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[1];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_abc[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[2];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_abc[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_dq0[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[1,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[1,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[1,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_dq0[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[2,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[2,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[2,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_dq0[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[3,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[3,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_rotation_matrix[3,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[1] = 0.816496580927726 * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[1] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[2] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[2] = 0.7071067811865475 * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[2] + (-0.7071067811865475) * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[3] = 0.5773502691896257 * (IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[3]);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[1,1] = cos(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[1,2] = sin(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[1,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[2,1] = -sin(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[2,2] = cos(IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_theta);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[2,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[3,1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[3,2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[3,3] = 1.0;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_abc[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[1];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_abc[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[2];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_abc[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_dq0[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[1,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[1,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[1,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_dq0[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[2,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[2,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[2,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_dq0[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[3,1] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[3,2] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_rotation_matrix[3,3] * IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_Concordia_phaseVar_AB0[3];
  der(IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_x) = IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_u / IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_T;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_y = IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_k * (IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_x + IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_u);
  der(IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y) = IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_k * IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_u;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Theta = (IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y);
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_theta = IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_y;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_abc[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[1];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_abc[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[2];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_abc[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[3];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_PLL_phaseVar_dq0[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_u;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Integrator_PLL_u = IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_y;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Ws = IEEE5bus_gridfeeding_GridFeeding2_PLL_PI_PLL_y;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_theta = IEEE5bus_gridfeeding_GridFeeding2_PLL_Theta;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_abc[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Is[1] / IEEE5bus_gridfeeding_GridFeeding2_PLL_Ib;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_abc[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Is[2] / IEEE5bus_gridfeeding_GridFeeding2_PLL_Ib;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_abc[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Is[3] / IEEE5bus_gridfeeding_GridFeeding2_PLL_Ib;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_isd = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_dq0[1];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_isq = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Current_phaseVar_dq0[2];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_theta = IEEE5bus_gridfeeding_GridFeeding2_PLL_Theta;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_abc[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[1] / IEEE5bus_gridfeeding_GridFeeding2_PLL_Vb;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_abc[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[2] / IEEE5bus_gridfeeding_GridFeeding2_PLL_Vb;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_abc[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[3] / IEEE5bus_gridfeeding_GridFeeding2_PLL_Vb;
  IEEE5bus_gridfeeding_GridFeeding2_PLL_vgd = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_dq0[1];
  IEEE5bus_gridfeeding_GridFeeding2_PLL_vgq = IEEE5bus_gridfeeding_GridFeeding2_PLL_Park_Voltage_phaseVar_dq0[2];
  IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_y = homotopy(smooth(0, if IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_u > IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_uMax then IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_uMax else if IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_u < IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_uMin then IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_uMin else IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_u), IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_u);
  IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_y = homotopy(smooth(0, if IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_u > IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_uMax then IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_uMax else if IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_u < IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_uMin then IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_uMin else IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_u), IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_u);
  IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_u = (-IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Pref) / (IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Sn * IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Vd_grid);
  IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_isd_ref = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_d_y;
  IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_u = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Qref / (IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Sn * IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Vd_grid);
  IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_isq_ref = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Current_Lim_q_y;
  der(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_y) = (IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_k * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_u - IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_y) / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_T;
  der(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_x) = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_u / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_T;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_y = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_k * (IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_x + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_u);
  der(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_y) = (IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_k * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_u - IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_y) / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_T;
  der(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_x) = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_u / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_T;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_y = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_k * (IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_x + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_u);
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[1] = 0.816496580927726 * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[1] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[2] + (-0.408248290463863) * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[2] = 0.7071067811865475 * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[2] + (-0.7071067811865475) * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[3] = 0.5773502691896257 * (IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[1] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[2] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[3]);
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[1,1] = cos(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_theta);
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[1,2] = sin(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_theta);
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[1,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[2,1] = -sin(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_theta);
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[2,2] = cos(IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_theta);
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[2,3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[3,1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[3,2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[3,3] = 1.0;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_abc[1] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[1];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_abc[2] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[2];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_abc[3] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_abc[3];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_dq0[1] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[1,1] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[1,2] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[1,3] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_dq0[2] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[2,1] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[2,2] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[2,3] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_dq0[3] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[3,1] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[1] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[3,2] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[2] + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_rotation_matrix[3,3] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_Concordia_phaseVar_AB0[3];
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_u = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isd_ref;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_u = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_d_y - IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isd;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vd_ref = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_d_y + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_vgd - IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ws * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isq * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Lf_pu / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_wb;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_u = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isq_ref;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_u = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fs_q_y - IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isq;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vq_ref = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_PI_sat_q_y + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ws * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isd * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Lf_pu / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_wb + IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_vgq;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_theta = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Theta;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_dq0[1] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vd_ref;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_dq0[2] = IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vq_ref;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_dq0[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fg[1] = 2.0 * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_abc[1] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vb / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vs;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fg[2] = 2.0 * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_abc[2] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vb / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vs;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_fg[3] = 2.0 * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Park_inv_phaseVar_abc[3] * IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vb / IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vs;
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_v[1] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[1] * IEEE5bus_gridfeeding_GridFeeding2_RL_converter_R + der(IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[1]) * IEEE5bus_gridfeeding_GridFeeding2_RL_converter_L;
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_v[2] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[2] * IEEE5bus_gridfeeding_GridFeeding2_RL_converter_R + der(IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[2]) * IEEE5bus_gridfeeding_GridFeeding2_RL_converter_L;
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_v[3] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[3] * IEEE5bus_gridfeeding_GridFeeding2_RL_converter_R + der(IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[3]) * IEEE5bus_gridfeeding_GridFeeding2_RL_converter_L;
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_v[1] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_v[1] - IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_v[2] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_v[2] - IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_v[3] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_v[3] - IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[3];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[1] + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_i[1];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[2] + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_i[2];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[3] + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[1] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[1];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[2] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[2];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_i[3] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[1] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[2] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[3] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_I[1] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_i[1];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_I[2] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_i[2];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_I[3] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_v[1] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[1] - IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_v[2] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[2] - IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_v[3] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[3] - IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[3];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[1] + IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_i[1];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[2] + IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_i[2];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[3] + IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_i[1] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[1];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_i[2] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[2];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_i[3] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_V[1] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_V[2] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_V[3] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_v[1] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[1] - IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_v[2] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[2] - IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_v[3] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[3] - IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_v[3];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[1] + IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[1];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[2] + IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[2];
  0.0 = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[3] + IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_i[1] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[1];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_i[2] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[2];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_i[3] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[3];
  IEEE5bus_gridfeeding_GridFeeding2_Ground_p_v[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Ground_p_v[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Ground_p_v[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Theta = IEEE5bus_gridfeeding_GridFeeding2_PLL_Theta;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Ws = IEEE5bus_gridfeeding_GridFeeding2_PLL_Ws;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_Vs = IEEE5bus_gridfeeding_GridFeeding2_Vs;
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_I[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Is[1];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_I[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Is[2];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_I[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Is[3];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_V[1] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[1];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_V[2] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[2];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_V[3] = IEEE5bus_gridfeeding_GridFeeding2_PLL_Vg[3];
  IEEE5bus_gridfeeding_cst2_y = IEEE5bus_gridfeeding_cst2_k;
  IEEE5bus_gridfeeding_StepPrefE1_y = IEEE5bus_gridfeeding_StepPrefE1_offset + (if time < IEEE5bus_gridfeeding_StepPrefE1_startTime then 0.0 else IEEE5bus_gridfeeding_StepPrefE1_height);
  IEEE5bus_gridfeeding_StepPrefE2_y = IEEE5bus_gridfeeding_StepPrefE2_offset + (if time < IEEE5bus_gridfeeding_StepPrefE2_startTime then 0.0 else IEEE5bus_gridfeeding_StepPrefE2_height);
  IEEE5bus_gridfeeding_StepQrefE1_y = IEEE5bus_gridfeeding_StepQrefE1_offset + (if time < IEEE5bus_gridfeeding_StepQrefE1_startTime then 0.0 else IEEE5bus_gridfeeding_StepQrefE1_height);
  IEEE5bus_gridfeeding_StepQrefE2_y = IEEE5bus_gridfeeding_StepQrefE2_offset + (if time < IEEE5bus_gridfeeding_StepQrefE2_startTime then 0.0 else IEEE5bus_gridfeeding_StepQrefE2_height);
  IEEE5bus_gridfeeding_GridFeeding2_Pref = IEEE5bus_gridfeeding_GridFeeding2_Pref0 + IEEE5bus_gridfeeding_StepPrefE1_y + IEEE5bus_gridfeeding_StepPrefE2_y;
  IEEE5bus_gridfeeding_GridFeeding2_Qref = IEEE5bus_gridfeeding_GridFeeding2_Qref0 + IEEE5bus_gridfeeding_StepQrefE1_y + IEEE5bus_gridfeeding_StepQrefE2_y;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_i[1] + IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_i[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_i[2] + IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_i[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_i[3] + IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_i[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_v[1] = IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_v[2] = IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_n_v[3] = IEEE5bus_gridfeeding_GridFeeding2_Conv_gd_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[1] + (-IEEE5bus_gridfeeding_GridFeeding2_Conv_p_i[1]) = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[2] + (-IEEE5bus_gridfeeding_GridFeeding2_Conv_p_i[2]) = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_i[3] + (-IEEE5bus_gridfeeding_GridFeeding2_Conv_p_i[3]) = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_v[1] = IEEE5bus_gridfeeding_GridFeeding2_Conv_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_v[2] = IEEE5bus_gridfeeding_GridFeeding2_Conv_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_VSource_p_v[3] = IEEE5bus_gridfeeding_GridFeeding2_Conv_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_Pref = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Pref;
  IEEE5bus_gridfeeding_GridFeeding2_Qref = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Qref;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_vgd = IEEE5bus_gridfeeding_GridFeeding2_PLL_vgd;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_vgd = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_Vd_grid;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isd_ref = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_isd_ref;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isq_ref = IEEE5bus_gridfeeding_GridFeeding2_RefCalculation_isq_ref;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_vgq = IEEE5bus_gridfeeding_GridFeeding2_PLL_vgq;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isd = IEEE5bus_gridfeeding_GridFeeding2_PLL_isd;
  IEEE5bus_gridfeeding_GridFeeding2_CurrentControl_isq = IEEE5bus_gridfeeding_GridFeeding2_PLL_isq;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_p_i[1] + IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_p_i[2] + IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_p_i[3] + IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_i[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Conv_p_v[1] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_p_v[2] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_Conv_p_v[3] = IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_i[1] + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_i[2] + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_i[3] + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_i[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[1] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[2] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_I_Sensor_n_v[3] = IEEE5bus_gridfeeding_GridFeeding2_RL_converter_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[1] + (-IEEE5bus_gridfeeding_GridFeeding2_p_i[1]) + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_i[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[2] + (-IEEE5bus_gridfeeding_GridFeeding2_p_i[2]) + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_i[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_i[3] + (-IEEE5bus_gridfeeding_GridFeeding2_p_i[3]) + IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_i[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[1] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[1] = IEEE5bus_gridfeeding_GridFeeding2_p_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[2] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[2] = IEEE5bus_gridfeeding_GridFeeding2_p_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[3] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_RL_converter_n_v[3] = IEEE5bus_gridfeeding_GridFeeding2_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[1] + IEEE5bus_gridfeeding_GridFeeding2_Ground_p_i[1] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[2] + IEEE5bus_gridfeeding_GridFeeding2_Ground_p_i[2] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_i[3] + IEEE5bus_gridfeeding_GridFeeding2_Ground_p_i[3] = 0.0;
  IEEE5bus_gridfeeding_GridFeeding2_Ground_p_v[1] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_v[1];
  IEEE5bus_gridfeeding_GridFeeding2_Ground_p_v[2] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_v[2];
  IEEE5bus_gridfeeding_GridFeeding2_Ground_p_v[3] = IEEE5bus_gridfeeding_GridFeeding2_V_Sensor_n_v[3];
  IEEE5bus_gridfeeding_Bus2_p_i[1] + IEEE5bus_gridfeeding_GridFeeding2_p_i[1] = 0.0;
  IEEE5bus_gridfeeding_Bus2_p_i[2] + IEEE5bus_gridfeeding_GridFeeding2_p_i[2] = 0.0;
  IEEE5bus_gridfeeding_Bus2_p_i[3] + IEEE5bus_gridfeeding_GridFeeding2_p_i[3] = 0.0;
  IEEE5bus_gridfeeding_Bus2_p_v[1] = IEEE5bus_gridfeeding_GridFeeding2_p_v[1];
  IEEE5bus_gridfeeding_Bus2_p_v[2] = IEEE5bus_gridfeeding_GridFeeding2_p_v[2];
  IEEE5bus_gridfeeding_Bus2_p_v[3] = IEEE5bus_gridfeeding_GridFeeding2_p_v[3];
  IEEE5bus_gridfeeding_GridFeeding2_Vs = IEEE5bus_gridfeeding_cst2_y;
  annotation(preferredView = "text");
end IEEE5bus_gridfeeding;
