/* Additional record code for GeneratorPQ_INIT generated by the OpenModelica Compiler OMCompiler v1.24.4. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "GeneratorPQ_INIT_functions.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Complex__desc_added 1
const char* Complex__desc__fields[2] = {"re","im"};
struct record_description Complex__desc = {
  "Complex", /* package_record__X */
  "Complex", /* package.record_X */
  Complex__desc__fields
};

void Complex_construct_p(threadData_t *threadData, void* v_ths ) {
  Complex* ths = (Complex*)(v_ths);
  // ths->_re has no default value.
  // ths->_im has no default value.
}

void Complex_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_re, modelica_real in_im) {
  Complex* dst = (Complex*)(v_dst);
  dst->_re = in_re;
  dst->_im = in_im;
}

void Complex_copy_p(void* v_src, void* v_dst) {
  Complex* src = (Complex*)(v_src);
  Complex* dst = (Complex*)(v_dst);
  dst->_re = src->_re;
  dst->_im = src->_im;
}


void Complex_1_2_construct_p(threadData_t *threadData, void* v_ths , modelica_real in_re, modelica_real in_im) {
  Complex* ths = (Complex*)(v_ths);
  ths->_re = in_re;
  ths->_im = in_im;
}

#define Dynawo_Connectors_ComplexCurrentPuConnector__desc_added 1
const char* Dynawo_Connectors_ComplexCurrentPuConnector__desc__fields[2] = {"re","im"};
struct record_description Dynawo_Connectors_ComplexCurrentPuConnector__desc = {
  "Dynawo_Connectors_ComplexCurrentPuConnector", /* package_record__X */
  "Dynawo.Connectors.ComplexCurrentPuConnector", /* package.record_X */
  Dynawo_Connectors_ComplexCurrentPuConnector__desc__fields
};

void Dynawo_Connectors_ComplexCurrentPuConnector_construct_p(threadData_t *threadData, void* v_ths ) {
  Dynawo_Connectors_ComplexCurrentPuConnector* ths = (Dynawo_Connectors_ComplexCurrentPuConnector*)(v_ths);
  // ths->_re has no default value.
  // ths->_im has no default value.
}

void Dynawo_Connectors_ComplexCurrentPuConnector_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_re, modelica_real in_im) {
  Dynawo_Connectors_ComplexCurrentPuConnector* dst = (Dynawo_Connectors_ComplexCurrentPuConnector*)(v_dst);
  dst->_re = in_re;
  dst->_im = in_im;
}

void Dynawo_Connectors_ComplexCurrentPuConnector_copy_p(void* v_src, void* v_dst) {
  Dynawo_Connectors_ComplexCurrentPuConnector* src = (Dynawo_Connectors_ComplexCurrentPuConnector*)(v_src);
  Dynawo_Connectors_ComplexCurrentPuConnector* dst = (Dynawo_Connectors_ComplexCurrentPuConnector*)(v_dst);
  dst->_re = src->_re;
  dst->_im = src->_im;
}


#define Dynawo_Connectors_ComplexVoltagePuConnector__desc_added 1
const char* Dynawo_Connectors_ComplexVoltagePuConnector__desc__fields[2] = {"re","im"};
struct record_description Dynawo_Connectors_ComplexVoltagePuConnector__desc = {
  "Dynawo_Connectors_ComplexVoltagePuConnector", /* package_record__X */
  "Dynawo.Connectors.ComplexVoltagePuConnector", /* package.record_X */
  Dynawo_Connectors_ComplexVoltagePuConnector__desc__fields
};

void Dynawo_Connectors_ComplexVoltagePuConnector_construct_p(threadData_t *threadData, void* v_ths ) {
  Dynawo_Connectors_ComplexVoltagePuConnector* ths = (Dynawo_Connectors_ComplexVoltagePuConnector*)(v_ths);
  // ths->_re has no default value.
  // ths->_im has no default value.
}

void Dynawo_Connectors_ComplexVoltagePuConnector_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_re, modelica_real in_im) {
  Dynawo_Connectors_ComplexVoltagePuConnector* dst = (Dynawo_Connectors_ComplexVoltagePuConnector*)(v_dst);
  dst->_re = in_re;
  dst->_im = in_im;
}

void Dynawo_Connectors_ComplexVoltagePuConnector_copy_p(void* v_src, void* v_dst) {
  Dynawo_Connectors_ComplexVoltagePuConnector* src = (Dynawo_Connectors_ComplexVoltagePuConnector*)(v_src);
  Dynawo_Connectors_ComplexVoltagePuConnector* dst = (Dynawo_Connectors_ComplexVoltagePuConnector*)(v_dst);
  dst->_re = src->_re;
  dst->_im = src->_im;
}


#define Dynawo_Types_ComplexApparentPowerPu__desc_added 1
const char* Dynawo_Types_ComplexApparentPowerPu__desc__fields[2] = {"re","im"};
struct record_description Dynawo_Types_ComplexApparentPowerPu__desc = {
  "Dynawo_Types_ComplexApparentPowerPu", /* package_record__X */
  "Dynawo.Types.ComplexApparentPowerPu", /* package.record_X */
  Dynawo_Types_ComplexApparentPowerPu__desc__fields
};

void Dynawo_Types_ComplexApparentPowerPu_construct_p(threadData_t *threadData, void* v_ths ) {
  Dynawo_Types_ComplexApparentPowerPu* ths = (Dynawo_Types_ComplexApparentPowerPu*)(v_ths);
  // ths->_re has no default value.
  // ths->_im has no default value.
}

void Dynawo_Types_ComplexApparentPowerPu_wrap_vars_p(threadData_t *threadData, void* v_dst , modelica_real in_re, modelica_real in_im) {
  Dynawo_Types_ComplexApparentPowerPu* dst = (Dynawo_Types_ComplexApparentPowerPu*)(v_dst);
  dst->_re = in_re;
  dst->_im = in_im;
}

void Dynawo_Types_ComplexApparentPowerPu_copy_p(void* v_src, void* v_dst) {
  Dynawo_Types_ComplexApparentPowerPu* src = (Dynawo_Types_ComplexApparentPowerPu*)(v_src);
  Dynawo_Types_ComplexApparentPowerPu* dst = (Dynawo_Types_ComplexApparentPowerPu*)(v_dst);
  dst->_re = src->_re;
  dst->_im = src->_im;
}

#ifdef __cplusplus
}
#endif
