//
// Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
// See AUTHORS.txt
// All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
//
// This file is part of Dynawo, an hybrid C++/Modelica open source time domain
// simulation tool for power systems.
//

/* Linear Systems */
/* Simulation code for MACHINE_PQ generated by the OpenModelica Compiler OMCompiler v1.9.4. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "MACHINE_PQ_functions.h"
#include "MACHINE_PQ_model.h"
#include "MACHINE_PQ_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif
#include "MACHINE_PQ_12jac.h"
#if defined(__cplusplus)
extern "C" {
#endif

/* initial linear systems */
void setLinearMatrixA30(void *inData, threadData_t *threadData, void *systemData)
{
  const int equationIndexes[2] = {1,30};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, (-$PMACHINE$Pterminal$PV$Pre), 0, linearSystemData, threadData);
  linearSystemData->setAElement(0, 1, $PMACHINE$Pterminal$PV$Pim, 1, linearSystemData, threadData);
  linearSystemData->setAElement(1, 0, $PMACHINE$Pterminal$PV$Pim, 2, linearSystemData, threadData);
  linearSystemData->setAElement(1, 1, $PMACHINE$Pterminal$PV$Pre, 3, linearSystemData, threadData);
}
void setLinearVectorb30(void *inData, threadData_t *threadData, void *systemData)
{
  const int equationIndexes[2] = {1,30};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setBElement(0, (-$PMACHINE$PSGenPu$Pim), linearSystemData, threadData);
  linearSystemData->setBElement(1, (-$PMACHINE$PSGenPu$Pre), linearSystemData, threadData);
}
void initializeStaticLSData30(void *inData, threadData_t *threadData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  int i=0;
  /* static ls data for $PMACHINE$Pterminal$Pi$Pim */
  linearSystemData->nominal[i] = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim.nominal;
  linearSystemData->min[i]     = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim.min;
  linearSystemData->max[i++]   = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim.max;
  /* static ls data for $PMACHINE$Pterminal$Pi$Pre */
  linearSystemData->nominal[i] = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre.nominal;
  linearSystemData->min[i]     = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre.min;
  linearSystemData->max[i++]   = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre.max;
}
/* initial_lambda0 linear systems */
/* parameter linear systems */
/* model linear systems */
void setLinearMatrixA69(void *inData, threadData_t *threadData, void *systemData)
{
  const int equationIndexes[2] = {1,69};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setAElement(0, 0, (-$PMACHINE$Pterminal$PV$Pre), 0, linearSystemData, threadData);
  linearSystemData->setAElement(0, 1, $PMACHINE$Pterminal$PV$Pim, 1, linearSystemData, threadData);
  linearSystemData->setAElement(1, 0, $PMACHINE$Pterminal$PV$Pim, 2, linearSystemData, threadData);
  linearSystemData->setAElement(1, 1, $PMACHINE$Pterminal$PV$Pre, 3, linearSystemData, threadData);
}
void setLinearVectorb69(void *inData, threadData_t *threadData, void *systemData)
{
  const int equationIndexes[2] = {1,69};
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  linearSystemData->setBElement(0, (-$PMACHINE$PSGenPu$Pim), linearSystemData, threadData);
  linearSystemData->setBElement(1, (-$PMACHINE$PSGenPu$Pre), linearSystemData, threadData);
}
void initializeStaticLSData69(void *inData, threadData_t *threadData, void *systemData)
{
  DATA* data = (DATA*) inData;
  LINEAR_SYSTEM_DATA* linearSystemData = (LINEAR_SYSTEM_DATA*) systemData;
  int i=0;
  /* static ls data for $PMACHINE$Pterminal$Pi$Pim */
  linearSystemData->nominal[i] = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim.nominal;
  linearSystemData->min[i]     = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim.min;
  linearSystemData->max[i++]   = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim.max;
  /* static ls data for $PMACHINE$Pterminal$Pi$Pre */
  linearSystemData->nominal[i] = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre.nominal;
  linearSystemData->min[i]     = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre.min;
  linearSystemData->max[i++]   = $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre.max;
}
/* jacobians linear systems */

/* funtion initialize linear systems */
void MACHINE_PQ_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA* linearSystemData)
{
  /* initial linear systems */
  assertStreamPrint(NULL, nLinearSystems > 0, "Internal Error: nLinearSystems mismatch!");
  linearSystemData[0].equationIndex = 30;
  linearSystemData[0].size = 2;
  linearSystemData[0].nnz = 4;
  linearSystemData[0].method = 0;
  linearSystemData[0].setA = setLinearMatrixA30;
  linearSystemData[0].setb = setLinearVectorb30;
  linearSystemData[0].initializeStaticLSData = initializeStaticLSData30;
  /* initial_lambda0 linear systems */
  /* parameter linear systems */
  /* model linear systems */
  assertStreamPrint(NULL, nLinearSystems > 1, "Internal Error: nLinearSystems mismatch!");
  linearSystemData[1].equationIndex = 69;
  linearSystemData[1].size = 2;
  linearSystemData[1].nnz = 4;
  linearSystemData[1].method = 0;
  linearSystemData[1].setA = setLinearMatrixA69;
  linearSystemData[1].setb = setLinearVectorb69;
  linearSystemData[1].initializeStaticLSData = initializeStaticLSData69;
  /* jacobians linear systems */
}

#if defined(__cplusplus)
}
#endif

