//
// Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
// See AUTHORS.txt
// All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
//
// This file is part of Dynawo, an hybrid C++/Modelica open source time domain
// simulation tool for power systems.
//

/* Main Simulation File */
/* Simulation code for MACHINE_PQ_INIT generated by the OpenModelica Compiler OMCompiler v1.9.4. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "MACHINE_PQ_INIT_functions.h"
#include "MACHINE_PQ_INIT_model.h"
#include "MACHINE_PQ_INIT_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define prefixedName_performSimulation MACHINE_PQ_INIT_performSimulation
#define prefixedName_updateContinuousSystem MACHINE_PQ_INIT_updateContinuousSystem
#include <simulation/solver/perform_simulation.c>

#define prefixedName_performQSSSimulation MACHINE_PQ_INIT_performQSSSimulation
#include <simulation/solver/perform_qss_simulation.c>

/* dummy VARINFO and FILEINFO */
const FILE_INFO dummyFILE_INFO = omc_dummyFileInfo;
const VAR_INFO dummyVAR_INFO = omc_dummyVarInfo;
#if defined(__cplusplus)
extern "C" {
#endif

int MACHINE_PQ_INIT_input_function(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}

int MACHINE_PQ_INIT_input_function_init(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}

int MACHINE_PQ_INIT_input_function_updateStartValues(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}

int MACHINE_PQ_INIT_inputNames(DATA *data, char ** names){
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}

int MACHINE_PQ_INIT_output_function(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}


/*
 equation index: 8
 type: SIMPLE_ASSIGN
 MACHINE._s0Pu._im = MACHINE.Q0Pu
 */
void MACHINE_PQ_INIT_eqFunction_8(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,8};
  $PMACHINE$Ps0Pu$Pim = $PMACHINE$PQ0Pu;
  TRACE_POP
}
/*
 equation index: 9
 type: SIMPLE_ASSIGN
 MACHINE._s0Pu._re = MACHINE.P0Pu
 */
void MACHINE_PQ_INIT_eqFunction_9(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,9};
  $PMACHINE$Ps0Pu$Pre = $PMACHINE$PP0Pu;
  TRACE_POP
}
/*
 equation index: 10
 type: SIMPLE_ASSIGN
 MACHINE._u0Pu._re = MACHINE.U0Pu * cos(MACHINE.UPhase0)
 */
void MACHINE_PQ_INIT_eqFunction_10(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,10};
  $PMACHINE$Pu0Pu$Pre = ($PMACHINE$PU0Pu) * (cos($PMACHINE$PUPhase0));
  TRACE_POP
}
/*
 equation index: 11
 type: SIMPLE_ASSIGN
 MACHINE._u0Pu._im = MACHINE.U0Pu * sin(MACHINE.UPhase0)
 */
void MACHINE_PQ_INIT_eqFunction_11(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,11};
  $PMACHINE$Pu0Pu$Pim = ($PMACHINE$PU0Pu) * (sin($PMACHINE$PUPhase0));
  TRACE_POP
}
/*
 equation index: 12
 type: LINEAR
 
 <var>MACHINE._i0Pu._re</var>
 <var>MACHINE._i0Pu._im</var>
 <row>
   <cell>-MACHINE.s0Pu.re</cell>
   <cell>-MACHINE.s0Pu.im</cell>
 </row>
 <matrix>
   <cell row="0" col="0">
     <residual>-MACHINE.u0Pu.re</residual>
   </cell><cell row="0" col="1">
     <residual>-MACHINE.u0Pu.im</residual>
   </cell><cell row="1" col="0">
     <residual>-MACHINE.u0Pu.im</residual>
   </cell><cell row="1" col="1">
     <residual>MACHINE.u0Pu.re</residual>
   </cell>
 </matrix>
 */
void MACHINE_PQ_INIT_eqFunction_12(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,12};
  /* Linear equation system */
  data->simulationInfo->linearSystemData[1].x[0] = _$PMACHINE$Pi0Pu$Pre(1);
  data->simulationInfo->linearSystemData[1].x[1] = _$PMACHINE$Pi0Pu$Pim(1);
  solve_linear_system(data, threadData, 1);
  $PMACHINE$Pi0Pu$Pre = data->simulationInfo->linearSystemData[1].x[0];
  $PMACHINE$Pi0Pu$Pim = data->simulationInfo->linearSystemData[1].x[1];
  TRACE_POP
}
/*
 equation index: 13
 type: SIMPLE_ASSIGN
 MACHINE._PGen0Pu = -MACHINE.P0Pu
 */
void MACHINE_PQ_INIT_eqFunction_13(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,13};
  $PMACHINE$PPGen0Pu = (-$PMACHINE$PP0Pu);
  TRACE_POP
}
/*
 equation index: 14
 type: SIMPLE_ASSIGN
 MACHINE._QGen0Pu = -MACHINE.Q0Pu
 */
void MACHINE_PQ_INIT_eqFunction_14(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,14};
  $PMACHINE$PQGen0Pu = (-$PMACHINE$PQ0Pu);
  TRACE_POP
}


int MACHINE_PQ_INIT_functionDAE(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  int equationIndexes[1] = {0};
  
  data->simulationInfo->needToIterate = 0;
  data->simulationInfo->discreteCall = 1;
  MACHINE_PQ_INIT_eqFunction_8(data, threadData);

  MACHINE_PQ_INIT_eqFunction_9(data, threadData);

  MACHINE_PQ_INIT_eqFunction_10(data, threadData);

  MACHINE_PQ_INIT_eqFunction_11(data, threadData);

  MACHINE_PQ_INIT_eqFunction_12(data, threadData);

  MACHINE_PQ_INIT_eqFunction_13(data, threadData);

  MACHINE_PQ_INIT_eqFunction_14(data, threadData);
  data->simulationInfo->discreteCall = 0;
  
  TRACE_POP
  return 0;
}

int MACHINE_PQ_INIT_symEulerUpdate(DATA *data, modelica_real dt)
{
  TRACE_PUSH
  #ifdef $P__OMC_DT
    $P__OMC_DT = dt;
  #else
    return -1;
  #endif
  
  TRACE_POP
  return 0;
}



int MACHINE_PQ_INIT_functionODE(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  data->simulationInfo->callStatistics.functionODE++;
  
  /* no ODE systems */

  
  TRACE_POP
  return 0;
}

#ifdef FMU_EXPERIMENTAL
#endif
/* forward the main in the simulation runtime */
extern int _main_SimulationRuntime(int argc, char**argv, DATA *data, threadData_t *threadData);

#include "MACHINE_PQ_INIT_12jac.h"
#include "MACHINE_PQ_INIT_13opt.h"

struct OpenModelicaGeneratedFunctionCallbacks MACHINE_PQ_INIT_callback = {
   (int (*)(DATA *, threadData_t *, void *)) MACHINE_PQ_INIT_performSimulation,
   (int (*)(DATA *, threadData_t *, void *)) MACHINE_PQ_INIT_performQSSSimulation,
   MACHINE_PQ_INIT_updateContinuousSystem,
   MACHINE_PQ_INIT_callExternalObjectConstructors,
   MACHINE_PQ_INIT_callExternalObjectDestructors,
   MACHINE_PQ_INIT_initialNonLinearSystem,
   MACHINE_PQ_INIT_initialLinearSystem,
   MACHINE_PQ_INIT_initialMixedSystem,
   MACHINE_PQ_INIT_initializeStateSets,
   MACHINE_PQ_INIT_functionODE,
   MACHINE_PQ_INIT_functionAlgebraics,
   MACHINE_PQ_INIT_functionDAE,
   MACHINE_PQ_INIT_input_function,
   MACHINE_PQ_INIT_input_function_init,
   MACHINE_PQ_INIT_input_function_updateStartValues,
   MACHINE_PQ_INIT_output_function,
   MACHINE_PQ_INIT_function_storeDelayed,
   MACHINE_PQ_INIT_updateBoundVariableAttributes,
   0 /* useHomotopy */,
   MACHINE_PQ_INIT_functionInitialEquations,
   MACHINE_PQ_INIT_functionInitialEquations_lambda0,
   MACHINE_PQ_INIT_functionRemovedInitialEquations,
   MACHINE_PQ_INIT_updateBoundParameters,
   MACHINE_PQ_INIT_checkForAsserts,
   MACHINE_PQ_INIT_function_ZeroCrossingsEquations,
   MACHINE_PQ_INIT_function_ZeroCrossings,
   MACHINE_PQ_INIT_function_updateRelations,
   MACHINE_PQ_INIT_checkForDiscreteChanges,
   MACHINE_PQ_INIT_zeroCrossingDescription,
   MACHINE_PQ_INIT_relationDescription,
   MACHINE_PQ_INIT_function_initSample,
   MACHINE_PQ_INIT_INDEX_JAC_A,
   MACHINE_PQ_INIT_INDEX_JAC_B,
   MACHINE_PQ_INIT_INDEX_JAC_C,
   MACHINE_PQ_INIT_INDEX_JAC_D,
   MACHINE_PQ_INIT_initialAnalyticJacobianA,
   MACHINE_PQ_INIT_initialAnalyticJacobianB,
   MACHINE_PQ_INIT_initialAnalyticJacobianC,
   MACHINE_PQ_INIT_initialAnalyticJacobianD,
   MACHINE_PQ_INIT_functionJacA_column,
   MACHINE_PQ_INIT_functionJacB_column,
   MACHINE_PQ_INIT_functionJacC_column,
   MACHINE_PQ_INIT_functionJacD_column,
   MACHINE_PQ_INIT_linear_model_frame,
   MACHINE_PQ_INIT_mayer,
   MACHINE_PQ_INIT_lagrange,
   MACHINE_PQ_INIT_pickUpBoundsForInputsInOptimization,
   MACHINE_PQ_INIT_setInputData,
   MACHINE_PQ_INIT_getTimeGrid,
   MACHINE_PQ_INIT_symEulerUpdate,
   MACHINE_PQ_INIT_function_initSynchronous,
   MACHINE_PQ_INIT_function_updateSynchronous,
   MACHINE_PQ_INIT_function_equationsSynchronous,
   NULL
   #ifdef FMU_EXPERIMENTAL
   ,MACHINE_PQ_INIT_functionODE_Partial
   ,MACHINE_PQ_INIT_functionFMIJacobian
   #endif
   ,MACHINE_PQ_INIT_inputNames


};

void MACHINE_PQ_INIT_setupDataStruc(DATA *data, threadData_t *threadData)
{
  assertStreamPrint(threadData,0!=data, "Error while initialize Data");
  data->callback = &MACHINE_PQ_INIT_callback;
  data->modelData->modelName = "MACHINE_PQ_INIT";
  data->modelData->modelFilePrefix = "MACHINE_PQ_INIT";
  data->modelData->resultFileName = NULL;
  data->modelData->modelDir = "/home/rosiereflo/Projects/devBranch/dynawo/dynawo/build/gcc7/master/Release/dynawo/sources/Models/Modelica/PreassembledModels";
  data->modelData->modelGUID = "{8c4e810f-3df3-4a00-8276-176fa3c9f9e0}";
  #if defined(OPENMODELICA_XML_FROM_FILE_AT_RUNTIME)
  data->modelData->initXMLData = NULL;
  data->modelData->modelDataXml.infoXMLData = NULL;
  #else
  data->modelData->initXMLData =
  #include "MACHINE_PQ_INIT_init.c"
  ;
  data->modelData->modelDataXml.infoXMLData =
  #include "MACHINE_PQ_INIT_info.c"
  ;
  #endif
  
  data->modelData->nStates = 0;
  data->modelData->nVariablesReal = 0+8+0 + 0;
  data->modelData->nDiscreteReal = 0;
  data->modelData->nVariablesInteger = 0;
  data->modelData->nVariablesBoolean = 0;
  data->modelData->nVariablesString = 0;
  data->modelData->nParametersReal = 4;
  data->modelData->nParametersInteger = 0;
  data->modelData->nParametersBoolean = 0;
  data->modelData->nParametersString = 0;
  data->modelData->nInputVars = 0;
  data->modelData->nOutputVars = 0;
  
  data->modelData->nAliasReal = 0;
  data->modelData->nAliasInteger = 0;
  data->modelData->nAliasBoolean = 0;
  data->modelData->nAliasString = 0;
  
  data->modelData->nZeroCrossings = 0;
  data->modelData->nSamples = 0;
  data->modelData->nRelations = 0;
  data->modelData->nMathEvents = 0;
  data->modelData->nExtObjs = 0;
  data->modelData->modelDataXml.fileName = "MACHINE_PQ_INIT_info.json";
  data->modelData->modelDataXml.modelInfoXmlLength = 0;
  data->modelData->modelDataXml.nFunctions = 4;
  data->modelData->modelDataXml.nProfileBlocks = 0;
  data->modelData->modelDataXml.nEquations = 15;
  data->modelData->nMixedSystems = 0;
  data->modelData->nLinearSystems = 2;
  data->modelData->nNonLinearSystems = 0;
  data->modelData->nStateSets = 0;
  data->modelData->nJacobians = 4;
  data->modelData->nOptimizeConstraints = 0;
  data->modelData->nOptimizeFinalConstraints = 0;
  
  data->modelData->nDelayExpressions = 0;
  
  data->modelData->nClocks = 0;
  data->modelData->nSubClocks = 0;
  
}

#ifdef __cplusplus
}
#endif

static int rml_execution_failed()
{
  fflush(NULL);
  fprintf(stderr, "Execution failed!\n");
  fflush(NULL);
  return 1;
}

#if defined(threadData)
#undef threadData
#endif
/* call the simulation runtime main from our main! */
int main(int argc, char**argv)
{
  int res;
  DATA data;
  MODEL_DATA modelData;
  SIMULATION_INFO simInfo;
  data.modelData = &modelData;
  data.simulationInfo = &simInfo;
  measure_time_flag = 0;
  MMC_INIT();omc_alloc_interface.init();
  {
    MMC_TRY_TOP()
  
    MMC_TRY_STACK()
  
    MACHINE_PQ_INIT_setupDataStruc(&data, threadData);
    res = _main_SimulationRuntime(argc, argv, &data, threadData);
    
    MMC_ELSE()
    rml_execution_failed();
    fprintf(stderr, "Stack overflow detected and was not caught.\nSend us a bug report at https://trac.openmodelica.org/OpenModelica/newticket\n    Include the following trace:\n");
    printStacktraceMessages();
    fflush(NULL);
    return 1;
    MMC_CATCH_STACK()
    
    MMC_CATCH_TOP(return rml_execution_failed());
  }

  fflush(NULL);
  EXIT(res);
  return res;
}

