//
// Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
// See AUTHORS.txt
// All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
//
// This file is part of Dynawo, an hybrid C++/Modelica open source time domain
// simulation tool for power systems.
//

/* Simulation code for MACHINE_PQ generated by the OpenModelica Compiler OMCompiler v1.9.4. */
/* StatesDerivatives */
/* der(MACHINE.omegaRefPu.value) */
#define _$P$DER$PMACHINE$PomegaRefPu$Pvalue(i) data->localData[i]->derivativesVars[0]
#define $P$DER$PMACHINE$PomegaRefPu$Pvalue _$P$DER$PMACHINE$PomegaRefPu$Pvalue(0)
#define $P$PRE$P$DER$PMACHINE$PomegaRefPu$Pvalue data->simulationInfo->derivativesVarsPre[0]
#define $P$ATTRIBUTE$P$DER$PMACHINE$PomegaRefPu$Pvalue data->modelData->derivativesVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$PMACHINE$PomegaRefPu$Pvalue $P$ATTRIBUTE$P$DER$PMACHINE$PomegaRefPu$Pvalue
#define $P$DER$PMACHINE$PomegaRefPu$Pvalue__varInfo data->modelData->derivativesVarsData[0].info
#define $P$PRE$P$DER$PMACHINE$PomegaRefPu$Pvalue__varInfo data->modelData->derivativesVarsData[0].info
#define _$P$PRE$P$DER$PMACHINE$PomegaRefPu$Pvalue(i) $P$PRE$P$DER$PMACHINE$PomegaRefPu$Pvalue


/* der(MACHINE.terminal.V.im) */
#define _$P$DER$PMACHINE$Pterminal$PV$Pim(i) data->localData[i]->derivativesVars[1]
#define $P$DER$PMACHINE$Pterminal$PV$Pim _$P$DER$PMACHINE$Pterminal$PV$Pim(0)
#define $P$PRE$P$DER$PMACHINE$Pterminal$PV$Pim data->simulationInfo->derivativesVarsPre[1]
#define $P$ATTRIBUTE$P$DER$PMACHINE$Pterminal$PV$Pim data->modelData->derivativesVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$PMACHINE$Pterminal$PV$Pim $P$ATTRIBUTE$P$DER$PMACHINE$Pterminal$PV$Pim
#define $P$DER$PMACHINE$Pterminal$PV$Pim__varInfo data->modelData->derivativesVarsData[1].info
#define $P$PRE$P$DER$PMACHINE$Pterminal$PV$Pim__varInfo data->modelData->derivativesVarsData[1].info
#define _$P$PRE$P$DER$PMACHINE$Pterminal$PV$Pim(i) $P$PRE$P$DER$PMACHINE$Pterminal$PV$Pim


/* der(MACHINE.terminal.V.re) */
#define _$P$DER$PMACHINE$Pterminal$PV$Pre(i) data->localData[i]->derivativesVars[2]
#define $P$DER$PMACHINE$Pterminal$PV$Pre _$P$DER$PMACHINE$Pterminal$PV$Pre(0)
#define $P$PRE$P$DER$PMACHINE$Pterminal$PV$Pre data->simulationInfo->derivativesVarsPre[2]
#define $P$ATTRIBUTE$P$DER$PMACHINE$Pterminal$PV$Pre data->modelData->derivativesVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$PMACHINE$Pterminal$PV$Pre $P$ATTRIBUTE$P$DER$PMACHINE$Pterminal$PV$Pre
#define $P$DER$PMACHINE$Pterminal$PV$Pre__varInfo data->modelData->derivativesVarsData[2].info
#define $P$PRE$P$DER$PMACHINE$Pterminal$PV$Pre__varInfo data->modelData->derivativesVarsData[2].info
#define _$P$PRE$P$DER$PMACHINE$Pterminal$PV$Pre(i) $P$PRE$P$DER$PMACHINE$Pterminal$PV$Pre


/* States */
/* MACHINE.omegaRefPu.value */
#define _$PMACHINE$PomegaRefPu$Pvalue(i) data->localData[i]->realVars[0]
#define $PMACHINE$PomegaRefPu$Pvalue _$PMACHINE$PomegaRefPu$Pvalue(0)
#define $P$PRE$PMACHINE$PomegaRefPu$Pvalue data->simulationInfo->realVarsPre[0]
#define $P$ATTRIBUTE$PMACHINE$PomegaRefPu$Pvalue data->modelData->realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PomegaRefPu$Pvalue $P$ATTRIBUTE$PMACHINE$PomegaRefPu$Pvalue
#define $PMACHINE$PomegaRefPu$Pvalue__varInfo data->modelData->realVarsData[0].info
#define $P$PRE$PMACHINE$PomegaRefPu$Pvalue__varInfo data->modelData->realVarsData[0].info
#define _$P$PRE$PMACHINE$PomegaRefPu$Pvalue(i) $P$PRE$PMACHINE$PomegaRefPu$Pvalue


/* MACHINE.terminal.V.im */
#define _$PMACHINE$Pterminal$PV$Pim(i) data->localData[i]->realVars[1]
#define $PMACHINE$Pterminal$PV$Pim _$PMACHINE$Pterminal$PV$Pim(0)
#define $P$PRE$PMACHINE$Pterminal$PV$Pim data->simulationInfo->realVarsPre[1]
#define $P$ATTRIBUTE$PMACHINE$Pterminal$PV$Pim data->modelData->realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pterminal$PV$Pim $P$ATTRIBUTE$PMACHINE$Pterminal$PV$Pim
#define $PMACHINE$Pterminal$PV$Pim__varInfo data->modelData->realVarsData[1].info
#define $P$PRE$PMACHINE$Pterminal$PV$Pim__varInfo data->modelData->realVarsData[1].info
#define _$P$PRE$PMACHINE$Pterminal$PV$Pim(i) $P$PRE$PMACHINE$Pterminal$PV$Pim


/* MACHINE.terminal.V.re */
#define _$PMACHINE$Pterminal$PV$Pre(i) data->localData[i]->realVars[2]
#define $PMACHINE$Pterminal$PV$Pre _$PMACHINE$Pterminal$PV$Pre(0)
#define $P$PRE$PMACHINE$Pterminal$PV$Pre data->simulationInfo->realVarsPre[2]
#define $P$ATTRIBUTE$PMACHINE$Pterminal$PV$Pre data->modelData->realVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pterminal$PV$Pre $P$ATTRIBUTE$PMACHINE$Pterminal$PV$Pre
#define $PMACHINE$Pterminal$PV$Pre__varInfo data->modelData->realVarsData[2].info
#define $P$PRE$PMACHINE$Pterminal$PV$Pre__varInfo data->modelData->realVarsData[2].info
#define _$P$PRE$PMACHINE$Pterminal$PV$Pre(i) $P$PRE$PMACHINE$Pterminal$PV$Pre


/* Non Discrete Real Algebraic Vars */
/* MACHINE.PGenPu */
#define _$PMACHINE$PPGenPu(i) data->localData[i]->realVars[3]
#define $PMACHINE$PPGenPu _$PMACHINE$PPGenPu(0)
#define $P$PRE$PMACHINE$PPGenPu data->simulationInfo->realVarsPre[3]
#define $P$ATTRIBUTE$PMACHINE$PPGenPu data->modelData->realVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PPGenPu $P$ATTRIBUTE$PMACHINE$PPGenPu
#define $PMACHINE$PPGenPu__varInfo data->modelData->realVarsData[3].info
#define $P$PRE$PMACHINE$PPGenPu__varInfo data->modelData->realVarsData[3].info
#define _$P$PRE$PMACHINE$PPGenPu(i) $P$PRE$PMACHINE$PPGenPu


/* MACHINE.PGenRawPu */
#define _$PMACHINE$PPGenRawPu(i) data->localData[i]->realVars[4]
#define $PMACHINE$PPGenRawPu _$PMACHINE$PPGenRawPu(0)
#define $P$PRE$PMACHINE$PPGenRawPu data->simulationInfo->realVarsPre[4]
#define $P$ATTRIBUTE$PMACHINE$PPGenRawPu data->modelData->realVarsData[4].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PPGenRawPu $P$ATTRIBUTE$PMACHINE$PPGenRawPu
#define $PMACHINE$PPGenRawPu__varInfo data->modelData->realVarsData[4].info
#define $P$PRE$PMACHINE$PPGenRawPu__varInfo data->modelData->realVarsData[4].info
#define _$P$PRE$PMACHINE$PPGenRawPu(i) $P$PRE$PMACHINE$PPGenRawPu


/* MACHINE.QGenPu */
#define _$PMACHINE$PQGenPu(i) data->localData[i]->realVars[5]
#define $PMACHINE$PQGenPu _$PMACHINE$PQGenPu(0)
#define $P$PRE$PMACHINE$PQGenPu data->simulationInfo->realVarsPre[5]
#define $P$ATTRIBUTE$PMACHINE$PQGenPu data->modelData->realVarsData[5].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PQGenPu $P$ATTRIBUTE$PMACHINE$PQGenPu
#define $PMACHINE$PQGenPu__varInfo data->modelData->realVarsData[5].info
#define $P$PRE$PMACHINE$PQGenPu__varInfo data->modelData->realVarsData[5].info
#define _$P$PRE$PMACHINE$PQGenPu(i) $P$PRE$PMACHINE$PQGenPu


/* MACHINE.SGenPu.im */
#define _$PMACHINE$PSGenPu$Pim(i) data->localData[i]->realVars[6]
#define $PMACHINE$PSGenPu$Pim _$PMACHINE$PSGenPu$Pim(0)
#define $P$PRE$PMACHINE$PSGenPu$Pim data->simulationInfo->realVarsPre[6]
#define $P$ATTRIBUTE$PMACHINE$PSGenPu$Pim data->modelData->realVarsData[6].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PSGenPu$Pim $P$ATTRIBUTE$PMACHINE$PSGenPu$Pim
#define $PMACHINE$PSGenPu$Pim__varInfo data->modelData->realVarsData[6].info
#define $P$PRE$PMACHINE$PSGenPu$Pim__varInfo data->modelData->realVarsData[6].info
#define _$P$PRE$PMACHINE$PSGenPu$Pim(i) $P$PRE$PMACHINE$PSGenPu$Pim


/* MACHINE.SGenPu.re */
#define _$PMACHINE$PSGenPu$Pre(i) data->localData[i]->realVars[7]
#define $PMACHINE$PSGenPu$Pre _$PMACHINE$PSGenPu$Pre(0)
#define $P$PRE$PMACHINE$PSGenPu$Pre data->simulationInfo->realVarsPre[7]
#define $P$ATTRIBUTE$PMACHINE$PSGenPu$Pre data->modelData->realVarsData[7].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PSGenPu$Pre $P$ATTRIBUTE$PMACHINE$PSGenPu$Pre
#define $PMACHINE$PSGenPu$Pre__varInfo data->modelData->realVarsData[7].info
#define $P$PRE$PMACHINE$PSGenPu$Pre__varInfo data->modelData->realVarsData[7].info
#define _$P$PRE$PMACHINE$PSGenPu$Pre(i) $P$PRE$PMACHINE$PSGenPu$Pre


/* MACHINE.UPu */
#define _$PMACHINE$PUPu(i) data->localData[i]->realVars[8]
#define $PMACHINE$PUPu _$PMACHINE$PUPu(0)
#define $P$PRE$PMACHINE$PUPu data->simulationInfo->realVarsPre[8]
#define $P$ATTRIBUTE$PMACHINE$PUPu data->modelData->realVarsData[8].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PUPu $P$ATTRIBUTE$PMACHINE$PUPu
#define $PMACHINE$PUPu__varInfo data->modelData->realVarsData[8].info
#define $P$PRE$PMACHINE$PUPu__varInfo data->modelData->realVarsData[8].info
#define _$P$PRE$PMACHINE$PUPu(i) $P$PRE$PMACHINE$PUPu


/* MACHINE.terminal.i.im */
#define _$PMACHINE$Pterminal$Pi$Pim(i) data->localData[i]->realVars[9]
#define $PMACHINE$Pterminal$Pi$Pim _$PMACHINE$Pterminal$Pi$Pim(0)
#define $P$PRE$PMACHINE$Pterminal$Pi$Pim data->simulationInfo->realVarsPre[9]
#define $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim data->modelData->realVarsData[9].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pterminal$Pi$Pim $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pim
#define $PMACHINE$Pterminal$Pi$Pim__varInfo data->modelData->realVarsData[9].info
#define $P$PRE$PMACHINE$Pterminal$Pi$Pim__varInfo data->modelData->realVarsData[9].info
#define _$P$PRE$PMACHINE$Pterminal$Pi$Pim(i) $P$PRE$PMACHINE$Pterminal$Pi$Pim


/* MACHINE.terminal.i.re */
#define _$PMACHINE$Pterminal$Pi$Pre(i) data->localData[i]->realVars[10]
#define $PMACHINE$Pterminal$Pi$Pre _$PMACHINE$Pterminal$Pi$Pre(0)
#define $P$PRE$PMACHINE$Pterminal$Pi$Pre data->simulationInfo->realVarsPre[10]
#define $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre data->modelData->realVarsData[10].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pterminal$Pi$Pre $P$ATTRIBUTE$PMACHINE$Pterminal$Pi$Pre
#define $PMACHINE$Pterminal$Pi$Pre__varInfo data->modelData->realVarsData[10].info
#define $P$PRE$PMACHINE$Pterminal$Pi$Pre__varInfo data->modelData->realVarsData[10].info
#define _$P$PRE$PMACHINE$Pterminal$Pi$Pre(i) $P$PRE$PMACHINE$Pterminal$Pi$Pre


/* Nonlinear Constraints For Dyn. Optimization */

/* Nonlinear Final Constraints For Dyn. Optimization */

/* Discrete Real Algebraic Vars */

/* Algebraic Integer Vars */
/* MACHINE.pStatus */
#define _$PMACHINE$PpStatus(i) data->localData[i]->integerDoubleVars[0]
#define $PMACHINE$PpStatus _$PMACHINE$PpStatus(0)
#define $P$PRE$PMACHINE$PpStatus data->simulationInfo->integerDoubleVarsPre[0]
#define $P$ATTRIBUTE$PMACHINE$PpStatus data->modelData->integerDoubleVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PpStatus $P$ATTRIBUTE$PMACHINE$PpStatus
#define $PMACHINE$PpStatus__varInfo data->modelData->integerDoubleVarsData[0].info
#define $P$PRE$PMACHINE$PpStatus__varInfo data->modelData->integerDoubleVarsData[0].info
#define _$P$PRE$PMACHINE$PpStatus(i) $P$PRE$PMACHINE$PpStatus


/* MACHINE.qStatus */
#define _$PMACHINE$PqStatus(i) data->localData[i]->integerDoubleVars[1]
#define $PMACHINE$PqStatus _$PMACHINE$PqStatus(0)
#define $P$PRE$PMACHINE$PqStatus data->simulationInfo->integerDoubleVarsPre[1]
#define $P$ATTRIBUTE$PMACHINE$PqStatus data->modelData->integerDoubleVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PqStatus $P$ATTRIBUTE$PMACHINE$PqStatus
#define $PMACHINE$PqStatus__varInfo data->modelData->integerDoubleVarsData[1].info
#define $P$PRE$PMACHINE$PqStatus__varInfo data->modelData->integerDoubleVarsData[1].info
#define _$P$PRE$PMACHINE$PqStatus(i) $P$PRE$PMACHINE$PqStatus


/* MACHINE.state */
#define _$PMACHINE$Pstate(i) data->localData[i]->integerDoubleVars[2]
#define $PMACHINE$Pstate _$PMACHINE$Pstate(0)
#define $P$PRE$PMACHINE$Pstate data->simulationInfo->integerDoubleVarsPre[2]
#define $P$ATTRIBUTE$PMACHINE$Pstate data->modelData->integerDoubleVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pstate $P$ATTRIBUTE$PMACHINE$Pstate
#define $PMACHINE$Pstate__varInfo data->modelData->integerDoubleVarsData[2].info
#define $P$PRE$PMACHINE$Pstate__varInfo data->modelData->integerDoubleVarsData[2].info
#define _$P$PRE$PMACHINE$Pstate(i) $P$PRE$PMACHINE$Pstate


/* Algebraic Parameter */
/* MACHINE.AlphaPu */
#define $PMACHINE$PAlphaPu data->simulationInfo->realParameter[0]
#define _$PMACHINE$PAlphaPu(i) $PMACHINE$PAlphaPu
#define $P$ATTRIBUTE$PMACHINE$PAlphaPu data->modelData->realParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PAlphaPu $P$ATTRIBUTE$PMACHINE$PAlphaPu
#define $PMACHINE$PAlphaPu__varInfo data->modelData->realParameterData[0].info


/* MACHINE.PGen0Pu */
#define $PMACHINE$PPGen0Pu data->simulationInfo->realParameter[1]
#define _$PMACHINE$PPGen0Pu(i) $PMACHINE$PPGen0Pu
#define $P$ATTRIBUTE$PMACHINE$PPGen0Pu data->modelData->realParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PPGen0Pu $P$ATTRIBUTE$PMACHINE$PPGen0Pu
#define $PMACHINE$PPGen0Pu__varInfo data->modelData->realParameterData[1].info


/* MACHINE.PMaxPu */
#define $PMACHINE$PPMaxPu data->simulationInfo->realParameter[2]
#define _$PMACHINE$PPMaxPu(i) $PMACHINE$PPMaxPu
#define $P$ATTRIBUTE$PMACHINE$PPMaxPu data->modelData->realParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PPMaxPu $P$ATTRIBUTE$PMACHINE$PPMaxPu
#define $PMACHINE$PPMaxPu__varInfo data->modelData->realParameterData[2].info


/* MACHINE.PMinPu */
#define $PMACHINE$PPMinPu data->simulationInfo->realParameter[3]
#define _$PMACHINE$PPMinPu(i) $PMACHINE$PPMinPu
#define $P$ATTRIBUTE$PMACHINE$PPMinPu data->modelData->realParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PPMinPu $P$ATTRIBUTE$PMACHINE$PPMinPu
#define $PMACHINE$PPMinPu__varInfo data->modelData->realParameterData[3].info


/* MACHINE.QGen0Pu */
#define $PMACHINE$PQGen0Pu data->simulationInfo->realParameter[4]
#define _$PMACHINE$PQGen0Pu(i) $PMACHINE$PQGen0Pu
#define $P$ATTRIBUTE$PMACHINE$PQGen0Pu data->modelData->realParameterData[4].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PQGen0Pu $P$ATTRIBUTE$PMACHINE$PQGen0Pu
#define $PMACHINE$PQGen0Pu__varInfo data->modelData->realParameterData[4].info


/* MACHINE.QMaxPu */
#define $PMACHINE$PQMaxPu data->simulationInfo->realParameter[5]
#define _$PMACHINE$PQMaxPu(i) $PMACHINE$PQMaxPu
#define $P$ATTRIBUTE$PMACHINE$PQMaxPu data->modelData->realParameterData[5].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PQMaxPu $P$ATTRIBUTE$PMACHINE$PQMaxPu
#define $PMACHINE$PQMaxPu__varInfo data->modelData->realParameterData[5].info


/* MACHINE.QMinPu */
#define $PMACHINE$PQMinPu data->simulationInfo->realParameter[6]
#define _$PMACHINE$PQMinPu(i) $PMACHINE$PQMinPu
#define $P$ATTRIBUTE$PMACHINE$PQMinPu data->modelData->realParameterData[6].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PQMinPu $P$ATTRIBUTE$PMACHINE$PQMinPu
#define $PMACHINE$PQMinPu__varInfo data->modelData->realParameterData[6].info


/* MACHINE.U0Pu */
#define $PMACHINE$PU0Pu data->simulationInfo->realParameter[7]
#define _$PMACHINE$PU0Pu(i) $PMACHINE$PU0Pu
#define $P$ATTRIBUTE$PMACHINE$PU0Pu data->modelData->realParameterData[7].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PU0Pu $P$ATTRIBUTE$PMACHINE$PU0Pu
#define $PMACHINE$PU0Pu__varInfo data->modelData->realParameterData[7].info


/* MACHINE.UMaxPu */
#define $PMACHINE$PUMaxPu data->simulationInfo->realParameter[8]
#define _$PMACHINE$PUMaxPu(i) $PMACHINE$PUMaxPu
#define $P$ATTRIBUTE$PMACHINE$PUMaxPu data->modelData->realParameterData[8].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PUMaxPu $P$ATTRIBUTE$PMACHINE$PUMaxPu
#define $PMACHINE$PUMaxPu__varInfo data->modelData->realParameterData[8].info


/* MACHINE.UMinPu */
#define $PMACHINE$PUMinPu data->simulationInfo->realParameter[9]
#define _$PMACHINE$PUMinPu(i) $PMACHINE$PUMinPu
#define $P$ATTRIBUTE$PMACHINE$PUMinPu data->modelData->realParameterData[9].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PUMinPu $P$ATTRIBUTE$PMACHINE$PUMinPu
#define $PMACHINE$PUMinPu__varInfo data->modelData->realParameterData[9].info


/* MACHINE.i0Pu.im */
#define $PMACHINE$Pi0Pu$Pim data->simulationInfo->realParameter[10]
#define _$PMACHINE$Pi0Pu$Pim(i) $PMACHINE$Pi0Pu$Pim
#define $P$ATTRIBUTE$PMACHINE$Pi0Pu$Pim data->modelData->realParameterData[10].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pi0Pu$Pim $P$ATTRIBUTE$PMACHINE$Pi0Pu$Pim
#define $PMACHINE$Pi0Pu$Pim__varInfo data->modelData->realParameterData[10].info


/* MACHINE.i0Pu.re */
#define $PMACHINE$Pi0Pu$Pre data->simulationInfo->realParameter[11]
#define _$PMACHINE$Pi0Pu$Pre(i) $PMACHINE$Pi0Pu$Pre
#define $P$ATTRIBUTE$PMACHINE$Pi0Pu$Pre data->modelData->realParameterData[11].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pi0Pu$Pre $P$ATTRIBUTE$PMACHINE$Pi0Pu$Pre
#define $PMACHINE$Pi0Pu$Pre__varInfo data->modelData->realParameterData[11].info


/* MACHINE.u0Pu.im */
#define $PMACHINE$Pu0Pu$Pim data->simulationInfo->realParameter[12]
#define _$PMACHINE$Pu0Pu$Pim(i) $PMACHINE$Pu0Pu$Pim
#define $P$ATTRIBUTE$PMACHINE$Pu0Pu$Pim data->modelData->realParameterData[12].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pu0Pu$Pim $P$ATTRIBUTE$PMACHINE$Pu0Pu$Pim
#define $PMACHINE$Pu0Pu$Pim__varInfo data->modelData->realParameterData[12].info


/* MACHINE.u0Pu.re */
#define $PMACHINE$Pu0Pu$Pre data->simulationInfo->realParameter[13]
#define _$PMACHINE$Pu0Pu$Pre(i) $PMACHINE$Pu0Pu$Pre
#define $P$ATTRIBUTE$PMACHINE$Pu0Pu$Pre data->modelData->realParameterData[13].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Pu0Pu$Pre $P$ATTRIBUTE$PMACHINE$Pu0Pu$Pre
#define $PMACHINE$Pu0Pu$Pre__varInfo data->modelData->realParameterData[13].info


/* External Objects */

/* Algebraic Integer Parameter */
/* MACHINE.NbSwitchOffSignals */
#define $PMACHINE$PNbSwitchOffSignals data->simulationInfo->integerParameter[0]
#define _$PMACHINE$PNbSwitchOffSignals(i) $PMACHINE$PNbSwitchOffSignals
#define $P$ATTRIBUTE$PMACHINE$PNbSwitchOffSignals data->modelData->integerParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PNbSwitchOffSignals $P$ATTRIBUTE$PMACHINE$PNbSwitchOffSignals
#define $PMACHINE$PNbSwitchOffSignals__varInfo data->modelData->integerParameterData[0].info


/* MACHINE.State0 */
#define $PMACHINE$PState0 data->simulationInfo->integerParameter[1]
#define _$PMACHINE$PState0(i) $PMACHINE$PState0
#define $P$ATTRIBUTE$PMACHINE$PState0 data->modelData->integerParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PState0 $P$ATTRIBUTE$PMACHINE$PState0
#define $PMACHINE$PState0__varInfo data->modelData->integerParameterData[1].info


/* Algebraic Boolean Vars */
/* $whenCondition1 */
#define _$P$whenCondition1(i) data->localData[i]->booleanVars[0]
#define $P$whenCondition1 _$P$whenCondition1(0)
#define $P$PRE$P$whenCondition1 data->simulationInfo->booleanVarsPre[0]
#define $P$ATTRIBUTE$P$whenCondition1 data->modelData->booleanVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition1 $P$ATTRIBUTE$P$whenCondition1
#define $P$whenCondition1__varInfo data->modelData->booleanVarsData[0].info
#define $P$PRE$P$whenCondition1__varInfo data->modelData->booleanVarsData[0].info
#define _$P$PRE$P$whenCondition1(i) $P$PRE$P$whenCondition1


/* $whenCondition10 */
#define _$P$whenCondition10(i) data->localData[i]->booleanVars[1]
#define $P$whenCondition10 _$P$whenCondition10(0)
#define $P$PRE$P$whenCondition10 data->simulationInfo->booleanVarsPre[1]
#define $P$ATTRIBUTE$P$whenCondition10 data->modelData->booleanVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition10 $P$ATTRIBUTE$P$whenCondition10
#define $P$whenCondition10__varInfo data->modelData->booleanVarsData[1].info
#define $P$PRE$P$whenCondition10__varInfo data->modelData->booleanVarsData[1].info
#define _$P$PRE$P$whenCondition10(i) $P$PRE$P$whenCondition10


/* $whenCondition2 */
#define _$P$whenCondition2(i) data->localData[i]->booleanVars[2]
#define $P$whenCondition2 _$P$whenCondition2(0)
#define $P$PRE$P$whenCondition2 data->simulationInfo->booleanVarsPre[2]
#define $P$ATTRIBUTE$P$whenCondition2 data->modelData->booleanVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition2 $P$ATTRIBUTE$P$whenCondition2
#define $P$whenCondition2__varInfo data->modelData->booleanVarsData[2].info
#define $P$PRE$P$whenCondition2__varInfo data->modelData->booleanVarsData[2].info
#define _$P$PRE$P$whenCondition2(i) $P$PRE$P$whenCondition2


/* $whenCondition3 */
#define _$P$whenCondition3(i) data->localData[i]->booleanVars[3]
#define $P$whenCondition3 _$P$whenCondition3(0)
#define $P$PRE$P$whenCondition3 data->simulationInfo->booleanVarsPre[3]
#define $P$ATTRIBUTE$P$whenCondition3 data->modelData->booleanVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition3 $P$ATTRIBUTE$P$whenCondition3
#define $P$whenCondition3__varInfo data->modelData->booleanVarsData[3].info
#define $P$PRE$P$whenCondition3__varInfo data->modelData->booleanVarsData[3].info
#define _$P$PRE$P$whenCondition3(i) $P$PRE$P$whenCondition3


/* $whenCondition4 */
#define _$P$whenCondition4(i) data->localData[i]->booleanVars[4]
#define $P$whenCondition4 _$P$whenCondition4(0)
#define $P$PRE$P$whenCondition4 data->simulationInfo->booleanVarsPre[4]
#define $P$ATTRIBUTE$P$whenCondition4 data->modelData->booleanVarsData[4].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition4 $P$ATTRIBUTE$P$whenCondition4
#define $P$whenCondition4__varInfo data->modelData->booleanVarsData[4].info
#define $P$PRE$P$whenCondition4__varInfo data->modelData->booleanVarsData[4].info
#define _$P$PRE$P$whenCondition4(i) $P$PRE$P$whenCondition4


/* $whenCondition5 */
#define _$P$whenCondition5(i) data->localData[i]->booleanVars[5]
#define $P$whenCondition5 _$P$whenCondition5(0)
#define $P$PRE$P$whenCondition5 data->simulationInfo->booleanVarsPre[5]
#define $P$ATTRIBUTE$P$whenCondition5 data->modelData->booleanVarsData[5].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition5 $P$ATTRIBUTE$P$whenCondition5
#define $P$whenCondition5__varInfo data->modelData->booleanVarsData[5].info
#define $P$PRE$P$whenCondition5__varInfo data->modelData->booleanVarsData[5].info
#define _$P$PRE$P$whenCondition5(i) $P$PRE$P$whenCondition5


/* $whenCondition6 */
#define _$P$whenCondition6(i) data->localData[i]->booleanVars[6]
#define $P$whenCondition6 _$P$whenCondition6(0)
#define $P$PRE$P$whenCondition6 data->simulationInfo->booleanVarsPre[6]
#define $P$ATTRIBUTE$P$whenCondition6 data->modelData->booleanVarsData[6].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition6 $P$ATTRIBUTE$P$whenCondition6
#define $P$whenCondition6__varInfo data->modelData->booleanVarsData[6].info
#define $P$PRE$P$whenCondition6__varInfo data->modelData->booleanVarsData[6].info
#define _$P$PRE$P$whenCondition6(i) $P$PRE$P$whenCondition6


/* $whenCondition7 */
#define _$P$whenCondition7(i) data->localData[i]->booleanVars[7]
#define $P$whenCondition7 _$P$whenCondition7(0)
#define $P$PRE$P$whenCondition7 data->simulationInfo->booleanVarsPre[7]
#define $P$ATTRIBUTE$P$whenCondition7 data->modelData->booleanVarsData[7].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition7 $P$ATTRIBUTE$P$whenCondition7
#define $P$whenCondition7__varInfo data->modelData->booleanVarsData[7].info
#define $P$PRE$P$whenCondition7__varInfo data->modelData->booleanVarsData[7].info
#define _$P$PRE$P$whenCondition7(i) $P$PRE$P$whenCondition7


/* $whenCondition8 */
#define _$P$whenCondition8(i) data->localData[i]->booleanVars[8]
#define $P$whenCondition8 _$P$whenCondition8(0)
#define $P$PRE$P$whenCondition8 data->simulationInfo->booleanVarsPre[8]
#define $P$ATTRIBUTE$P$whenCondition8 data->modelData->booleanVarsData[8].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition8 $P$ATTRIBUTE$P$whenCondition8
#define $P$whenCondition8__varInfo data->modelData->booleanVarsData[8].info
#define $P$PRE$P$whenCondition8__varInfo data->modelData->booleanVarsData[8].info
#define _$P$PRE$P$whenCondition8(i) $P$PRE$P$whenCondition8


/* $whenCondition9 */
#define _$P$whenCondition9(i) data->localData[i]->booleanVars[9]
#define $P$whenCondition9 _$P$whenCondition9(0)
#define $P$PRE$P$whenCondition9 data->simulationInfo->booleanVarsPre[9]
#define $P$ATTRIBUTE$P$whenCondition9 data->modelData->booleanVarsData[9].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition9 $P$ATTRIBUTE$P$whenCondition9
#define $P$whenCondition9__varInfo data->modelData->booleanVarsData[9].info
#define $P$PRE$P$whenCondition9__varInfo data->modelData->booleanVarsData[9].info
#define _$P$PRE$P$whenCondition9(i) $P$PRE$P$whenCondition9


/* MACHINE.running.value */
#define _$PMACHINE$Prunning$Pvalue(i) data->localData[i]->booleanVars[10]
#define $PMACHINE$Prunning$Pvalue _$PMACHINE$Prunning$Pvalue(0)
#define $P$PRE$PMACHINE$Prunning$Pvalue data->simulationInfo->booleanVarsPre[10]
#define $P$ATTRIBUTE$PMACHINE$Prunning$Pvalue data->modelData->booleanVarsData[10].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$Prunning$Pvalue $P$ATTRIBUTE$PMACHINE$Prunning$Pvalue
#define $PMACHINE$Prunning$Pvalue__varInfo data->modelData->booleanVarsData[10].info
#define $P$PRE$PMACHINE$Prunning$Pvalue__varInfo data->modelData->booleanVarsData[10].info
#define _$P$PRE$PMACHINE$Prunning$Pvalue(i) $P$PRE$PMACHINE$Prunning$Pvalue


/* MACHINE.switchOffSignal1.value */
#define _$PMACHINE$PswitchOffSignal1$Pvalue(i) data->localData[i]->booleanVars[11]
#define $PMACHINE$PswitchOffSignal1$Pvalue _$PMACHINE$PswitchOffSignal1$Pvalue(0)
#define $P$PRE$PMACHINE$PswitchOffSignal1$Pvalue data->simulationInfo->booleanVarsPre[11]
#define $P$ATTRIBUTE$PMACHINE$PswitchOffSignal1$Pvalue data->modelData->booleanVarsData[11].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PswitchOffSignal1$Pvalue $P$ATTRIBUTE$PMACHINE$PswitchOffSignal1$Pvalue
#define $PMACHINE$PswitchOffSignal1$Pvalue__varInfo data->modelData->booleanVarsData[11].info
#define $P$PRE$PMACHINE$PswitchOffSignal1$Pvalue__varInfo data->modelData->booleanVarsData[11].info
#define _$P$PRE$PMACHINE$PswitchOffSignal1$Pvalue(i) $P$PRE$PMACHINE$PswitchOffSignal1$Pvalue


/* MACHINE.switchOffSignal2.value */
#define _$PMACHINE$PswitchOffSignal2$Pvalue(i) data->localData[i]->booleanVars[12]
#define $PMACHINE$PswitchOffSignal2$Pvalue _$PMACHINE$PswitchOffSignal2$Pvalue(0)
#define $P$PRE$PMACHINE$PswitchOffSignal2$Pvalue data->simulationInfo->booleanVarsPre[12]
#define $P$ATTRIBUTE$PMACHINE$PswitchOffSignal2$Pvalue data->modelData->booleanVarsData[12].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PswitchOffSignal2$Pvalue $P$ATTRIBUTE$PMACHINE$PswitchOffSignal2$Pvalue
#define $PMACHINE$PswitchOffSignal2$Pvalue__varInfo data->modelData->booleanVarsData[12].info
#define $P$PRE$PMACHINE$PswitchOffSignal2$Pvalue__varInfo data->modelData->booleanVarsData[12].info
#define _$P$PRE$PMACHINE$PswitchOffSignal2$Pvalue(i) $P$PRE$PMACHINE$PswitchOffSignal2$Pvalue


/* MACHINE.switchOffSignal3.value */
#define _$PMACHINE$PswitchOffSignal3$Pvalue(i) data->localData[i]->booleanVars[13]
#define $PMACHINE$PswitchOffSignal3$Pvalue _$PMACHINE$PswitchOffSignal3$Pvalue(0)
#define $P$PRE$PMACHINE$PswitchOffSignal3$Pvalue data->simulationInfo->booleanVarsPre[13]
#define $P$ATTRIBUTE$PMACHINE$PswitchOffSignal3$Pvalue data->modelData->booleanVarsData[13].attribute
#define $P$ATTRIBUTE$P$PRE$PMACHINE$PswitchOffSignal3$Pvalue $P$ATTRIBUTE$PMACHINE$PswitchOffSignal3$Pvalue
#define $PMACHINE$PswitchOffSignal3$Pvalue__varInfo data->modelData->booleanVarsData[13].info
#define $P$PRE$PMACHINE$PswitchOffSignal3$Pvalue__varInfo data->modelData->booleanVarsData[13].info
#define _$P$PRE$PMACHINE$PswitchOffSignal3$Pvalue(i) $P$PRE$PMACHINE$PswitchOffSignal3$Pvalue


/* Algebraic Boolean Parameters */

/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */

#define Dynawo_Types_AC_ApparentPower$MACHINE$SGenPu_index 0
#define Complex_index 1
#define Dynawo_Types_AC_ApparentPower_index 2
#define Dynawo_NonElectrical_Logs_Timeline_logEvent1_index 3
#define Dynawo_Types_AC_Current$MACHINE$terminal$i_index 4
#define Dynawo_Types_AC_Current_index 5
#define Dynawo_Types_AC_Voltage_index 6
#define Dynawo_Types_AC_Voltage$MACHINE$terminal$V_index 7

extern void MACHINE_PQ_callExternalObjectConstructors(DATA *data, threadData_t *threadData);
extern void MACHINE_PQ_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
extern void MACHINE_PQ_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
extern void MACHINE_PQ_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
extern void MACHINE_PQ_initialMixedSystem(int nMixedSystems, MIXED_SYSTEM_DATA *data);
extern void MACHINE_PQ_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
extern int MACHINE_PQ_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_checkForAsserts(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int MACHINE_PQ_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern int MACHINE_PQ_checkForDiscreteChanges(DATA *data, threadData_t *threadData);
extern const char* MACHINE_PQ_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* MACHINE_PQ_relationDescription(int i);
extern void MACHINE_PQ_function_initSample(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int MACHINE_PQ_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int MACHINE_PQ_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int MACHINE_PQ_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int MACHINE_PQ_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int MACHINE_PQ_functionJacG_column(void* data, threadData_t *threadData);
extern int MACHINE_PQ_functionJacA_column(void* data, threadData_t *threadData);
extern int MACHINE_PQ_functionJacB_column(void* data, threadData_t *threadData);
extern int MACHINE_PQ_functionJacC_column(void* data, threadData_t *threadData);
extern int MACHINE_PQ_functionJacD_column(void* data, threadData_t *threadData);
extern const char* MACHINE_PQ_linear_model_frame(void);
extern int MACHINE_PQ_mayer(DATA* data, modelica_real** res, short *);
extern int MACHINE_PQ_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int MACHINE_PQ_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int MACHINE_PQ_setInputData(DATA *data, const modelica_boolean file);
extern int MACHINE_PQ_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void MACHINE_PQ_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void MACHINE_PQ_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int MACHINE_PQ_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void MACHINE_PQ_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void MACHINE_PQ_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int MACHINE_PQ_inputNames(DATA* data, char ** names);

