//
// Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
// See AUTHORS.txt
// All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
//
// This file is part of Dynawo, an hybrid C++/Modelica open source time domain
// simulation tool for power systems.
//

/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for MACHINE_PQ generated by the OpenModelica Compiler OMCompiler v1.9.4. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "MACHINE_PQ_functions.h"
#include "MACHINE_PQ_model.h"
#include "MACHINE_PQ_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif
#if defined(__cplusplus)
extern "C" {
#endif

/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void MACHINE_PQ_function_initSample(DATA *data, threadData_t *threadData)
{
  long i=0;
}

const char *MACHINE_PQ_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  static const char *res[] = {"time > 999999.0",
  "MACHINE.PGenRawPu >= MACHINE.PMaxPu and pre(MACHINE.pStatus) <> Dynawo.Electrical.Machines.GeneratorPQ.PStatus.limitPMax",
  "MACHINE.PGenRawPu <= MACHINE.PMinPu and pre(MACHINE.pStatus) <> Dynawo.Electrical.Machines.GeneratorPQ.PStatus.limitPMin",
  "MACHINE.PGenRawPu > MACHINE.PMinPu and pre(MACHINE.pStatus) == Dynawo.Electrical.Machines.GeneratorPQ.PStatus.limitPMin",
  "MACHINE.PGenRawPu < MACHINE.PMaxPu and pre(MACHINE.pStatus) == Dynawo.Electrical.Machines.GeneratorPQ.PStatus.limitPMax",
  "MACHINE.UPu >= 0.0001 + MACHINE.UMaxPu and pre(MACHINE.qStatus) <> Dynawo.Electrical.Machines.GeneratorPQ.QStatus.absorptionMax",
  "MACHINE.UPu <= -0.0001 + MACHINE.UMinPu and pre(MACHINE.qStatus) <> Dynawo.Electrical.Machines.GeneratorPQ.QStatus.generationMax",
  "MACHINE.UPu < -0.0001 + MACHINE.UMaxPu and pre(MACHINE.qStatus) == Dynawo.Electrical.Machines.GeneratorPQ.QStatus.absorptionMax or MACHINE.UPu > 0.0001 + MACHINE.UMinPu and pre(MACHINE.qStatus) == Dynawo.Electrical.Machines.GeneratorPQ.QStatus.generationMax"};
  static const int occurEqs0[] = {1,38};
  static const int occurEqs1[] = {1,50};
  static const int occurEqs2[] = {1,51};
  static const int occurEqs3[] = {1,52};
  static const int occurEqs4[] = {1,53};
  static const int occurEqs5[] = {1,60};
  static const int occurEqs6[] = {1,61};
  static const int occurEqs7[] = {1,62};
  static const int *occurEqs[] = {occurEqs0,occurEqs1,occurEqs2,occurEqs3,occurEqs4,occurEqs5,occurEqs6,occurEqs7};
  *out_EquationIndexes = (int*) occurEqs[i];
  return res[i];
}

/* forwarded equations */
extern void MACHINE_PQ_eqFunction_38(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_42(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_46(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_47(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_48(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_49(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_50(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_51(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_52(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_53(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_59(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_60(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_61(DATA* data, threadData_t *threadData);
extern void MACHINE_PQ_eqFunction_62(DATA* data, threadData_t *threadData);

int MACHINE_PQ_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  
  data->simulationInfo->callStatistics.functionZeroCrossingsEquations++;
  
  MACHINE_PQ_eqFunction_38(data, threadData);

  MACHINE_PQ_eqFunction_42(data, threadData);

  MACHINE_PQ_eqFunction_46(data, threadData);

  MACHINE_PQ_eqFunction_47(data, threadData);

  MACHINE_PQ_eqFunction_48(data, threadData);

  MACHINE_PQ_eqFunction_49(data, threadData);

  MACHINE_PQ_eqFunction_50(data, threadData);

  MACHINE_PQ_eqFunction_51(data, threadData);

  MACHINE_PQ_eqFunction_52(data, threadData);

  MACHINE_PQ_eqFunction_53(data, threadData);

  MACHINE_PQ_eqFunction_59(data, threadData);

  MACHINE_PQ_eqFunction_60(data, threadData);

  MACHINE_PQ_eqFunction_61(data, threadData);

  MACHINE_PQ_eqFunction_62(data, threadData);
  
  TRACE_POP
  return 0;
}

int MACHINE_PQ_function_ZeroCrossings(DATA *data, threadData_t *threadData, double *gout)
{
  TRACE_PUSH
  modelica_boolean tmp1053;
  modelica_boolean tmp1054;
  modelica_boolean tmp1056;
  modelica_boolean tmp1058;
  modelica_boolean tmp1060;
  modelica_boolean tmp1062;
  modelica_boolean tmp1064;
  modelica_boolean tmp1066;
  modelica_boolean tmp1068;
  
  data->simulationInfo->callStatistics.functionZeroCrossings++;
  
  tmp1053 = GreaterZC(data->localData[0]->timeValue, 999999.0, data->simulationInfo->storedRelations[0]);
  gout[0] = (tmp1053) ? 1 : -1;
  tmp1054 = GreaterEqZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMaxPu, data->simulationInfo->storedRelations[1]);
  gout[1] = ((tmp1054 && ($P$PRE$PMACHINE$PpStatus != 3))) ? 1 : -1;
  tmp1056 = LessEqZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMinPu, data->simulationInfo->storedRelations[2]);
  gout[2] = ((tmp1056 && ($P$PRE$PMACHINE$PpStatus != 2))) ? 1 : -1;
  tmp1058 = GreaterZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMinPu, data->simulationInfo->storedRelations[3]);
  gout[3] = ((tmp1058 && ($P$PRE$PMACHINE$PpStatus == 2))) ? 1 : -1;
  tmp1060 = LessZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMaxPu, data->simulationInfo->storedRelations[4]);
  gout[4] = ((tmp1060 && ($P$PRE$PMACHINE$PpStatus == 3))) ? 1 : -1;
  tmp1062 = GreaterEqZC($PMACHINE$PUPu, 0.0001 + $PMACHINE$PUMaxPu, data->simulationInfo->storedRelations[5]);
  gout[5] = ((tmp1062 && ($P$PRE$PMACHINE$PqStatus != 2))) ? 1 : -1;
  tmp1064 = LessEqZC($PMACHINE$PUPu, -0.0001 + $PMACHINE$PUMinPu, data->simulationInfo->storedRelations[6]);
  gout[6] = ((tmp1064 && ($P$PRE$PMACHINE$PqStatus != 3))) ? 1 : -1;
  tmp1066 = LessZC($PMACHINE$PUPu, -0.0001 + $PMACHINE$PUMaxPu, data->simulationInfo->storedRelations[7]);
  tmp1068 = GreaterZC($PMACHINE$PUPu, 0.0001 + $PMACHINE$PUMinPu, data->simulationInfo->storedRelations[8]);
  gout[7] = (((tmp1066 && ($P$PRE$PMACHINE$PqStatus == 2)) || (tmp1068 && ($P$PRE$PMACHINE$PqStatus == 3)))) ? 1 : -1;
  
  TRACE_POP
  return 0;
}

const char *MACHINE_PQ_relationDescription(int i)
{
  const char *res[] = {"time > 999999.0",
  "MACHINE.PGenRawPu >= MACHINE.PMaxPu",
  "MACHINE.PGenRawPu <= MACHINE.PMinPu",
  "MACHINE.PGenRawPu > MACHINE.PMinPu",
  "MACHINE.PGenRawPu < MACHINE.PMaxPu",
  "MACHINE.UPu >= 0.0001 + MACHINE.UMaxPu",
  "MACHINE.UPu <= -0.0001 + MACHINE.UMinPu",
  "MACHINE.UPu < -0.0001 + MACHINE.UMaxPu",
  "MACHINE.UPu > 0.0001 + MACHINE.UMinPu"};
  return res[i];
}

int MACHINE_PQ_function_updateRelations(DATA *data, threadData_t *threadData, int evalforZeroCross)
{
  TRACE_PUSH
  modelica_boolean tmp1070;
  modelica_boolean tmp1071;
  modelica_boolean tmp1072;
  modelica_boolean tmp1073;
  modelica_boolean tmp1074;
  modelica_boolean tmp1075;
  modelica_boolean tmp1076;
  modelica_boolean tmp1077;
  modelica_boolean tmp1078;
  
  if(evalforZeroCross) {
    tmp1070 = GreaterZC(data->localData[0]->timeValue, 999999.0, data->simulationInfo->storedRelations[0]);
    data->simulationInfo->relations[0] = tmp1070;
    tmp1071 = GreaterEqZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMaxPu, data->simulationInfo->storedRelations[1]);
    data->simulationInfo->relations[1] = tmp1071;
    tmp1072 = LessEqZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMinPu, data->simulationInfo->storedRelations[2]);
    data->simulationInfo->relations[2] = tmp1072;
    tmp1073 = GreaterZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMinPu, data->simulationInfo->storedRelations[3]);
    data->simulationInfo->relations[3] = tmp1073;
    tmp1074 = LessZC($PMACHINE$PPGenRawPu, $PMACHINE$PPMaxPu, data->simulationInfo->storedRelations[4]);
    data->simulationInfo->relations[4] = tmp1074;
    tmp1075 = GreaterEqZC($PMACHINE$PUPu, 0.0001 + $PMACHINE$PUMaxPu, data->simulationInfo->storedRelations[5]);
    data->simulationInfo->relations[5] = tmp1075;
    tmp1076 = LessEqZC($PMACHINE$PUPu, -0.0001 + $PMACHINE$PUMinPu, data->simulationInfo->storedRelations[6]);
    data->simulationInfo->relations[6] = tmp1076;
    tmp1077 = LessZC($PMACHINE$PUPu, -0.0001 + $PMACHINE$PUMaxPu, data->simulationInfo->storedRelations[7]);
    data->simulationInfo->relations[7] = tmp1077;
    tmp1078 = GreaterZC($PMACHINE$PUPu, 0.0001 + $PMACHINE$PUMinPu, data->simulationInfo->storedRelations[8]);
    data->simulationInfo->relations[8] = tmp1078;
  } else {
    data->simulationInfo->relations[0] = (data->localData[0]->timeValue > 999999.0);
    data->simulationInfo->relations[1] = ($PMACHINE$PPGenRawPu >= $PMACHINE$PPMaxPu);
    data->simulationInfo->relations[2] = ($PMACHINE$PPGenRawPu <= $PMACHINE$PPMinPu);
    data->simulationInfo->relations[3] = ($PMACHINE$PPGenRawPu > $PMACHINE$PPMinPu);
    data->simulationInfo->relations[4] = ($PMACHINE$PPGenRawPu < $PMACHINE$PPMaxPu);
    data->simulationInfo->relations[5] = ($PMACHINE$PUPu >= 0.0001 + $PMACHINE$PUMaxPu);
    data->simulationInfo->relations[6] = ($PMACHINE$PUPu <= -0.0001 + $PMACHINE$PUMinPu);
    data->simulationInfo->relations[7] = ($PMACHINE$PUPu < -0.0001 + $PMACHINE$PUMaxPu);
    data->simulationInfo->relations[8] = ($PMACHINE$PUPu > 0.0001 + $PMACHINE$PUMinPu);
  }
  
  TRACE_POP
  return 0;
}

int MACHINE_PQ_checkForDiscreteChanges(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  int needToIterate = 0;

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes at time=%.12g", data->localData[0]->timeValue);
  if($P$whenCondition8 != $P$PRE$P$whenCondition8)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition8 from %d to %d", $P$PRE$P$whenCondition8, $P$whenCondition8);
    needToIterate = 1;
  }
  if($P$whenCondition9 != $P$PRE$P$whenCondition9)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition9 from %d to %d", $P$PRE$P$whenCondition9, $P$whenCondition9);
    needToIterate = 1;
  }
  if($P$whenCondition10 != $P$PRE$P$whenCondition10)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition10 from %d to %d", $P$PRE$P$whenCondition10, $P$whenCondition10);
    needToIterate = 1;
  }
  if($P$whenCondition7 != $P$PRE$P$whenCondition7)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition7 from %d to %d", $P$PRE$P$whenCondition7, $P$whenCondition7);
    needToIterate = 1;
  }
  if($P$whenCondition6 != $P$PRE$P$whenCondition6)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition6 from %d to %d", $P$PRE$P$whenCondition6, $P$whenCondition6);
    needToIterate = 1;
  }
  if($P$whenCondition2 != $P$PRE$P$whenCondition2)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition2 from %d to %d", $P$PRE$P$whenCondition2, $P$whenCondition2);
    needToIterate = 1;
  }
  if($P$whenCondition3 != $P$PRE$P$whenCondition3)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition3 from %d to %d", $P$PRE$P$whenCondition3, $P$whenCondition3);
    needToIterate = 1;
  }
  if($P$whenCondition4 != $P$PRE$P$whenCondition4)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition4 from %d to %d", $P$PRE$P$whenCondition4, $P$whenCondition4);
    needToIterate = 1;
  }
  if($P$whenCondition5 != $P$PRE$P$whenCondition5)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition5 from %d to %d", $P$PRE$P$whenCondition5, $P$whenCondition5);
    needToIterate = 1;
  }
  if($P$whenCondition1 != $P$PRE$P$whenCondition1)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition1 from %d to %d", $P$PRE$P$whenCondition1, $P$whenCondition1);
    needToIterate = 1;
  }
  if($PMACHINE$PswitchOffSignal1$Pvalue != $P$PRE$PMACHINE$PswitchOffSignal1$Pvalue)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MACHINE._switchOffSignal1._value from %d to %d", $P$PRE$PMACHINE$PswitchOffSignal1$Pvalue, $PMACHINE$PswitchOffSignal1$Pvalue);
    needToIterate = 1;
  }
  if($PMACHINE$Prunning$Pvalue != $P$PRE$PMACHINE$Prunning$Pvalue)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MACHINE._running._value from %d to %d", $P$PRE$PMACHINE$Prunning$Pvalue, $PMACHINE$Prunning$Pvalue);
    needToIterate = 1;
  }
  if($PMACHINE$Pstate != $P$PRE$PMACHINE$Pstate)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MACHINE._state from %ld to %ld", $P$PRE$PMACHINE$Pstate, $PMACHINE$Pstate);
    needToIterate = 1;
  }
  if($PMACHINE$PpStatus != $P$PRE$PMACHINE$PpStatus)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MACHINE._pStatus from %ld to %ld", $P$PRE$PMACHINE$PpStatus, $PMACHINE$PpStatus);
    needToIterate = 1;
  }
  if($PMACHINE$PqStatus != $P$PRE$PMACHINE$PqStatus)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MACHINE._qStatus from %ld to %ld", $P$PRE$PMACHINE$PqStatus, $PMACHINE$PqStatus);
    needToIterate = 1;
  }
  if($PMACHINE$PswitchOffSignal2$Pvalue != $P$PRE$PMACHINE$PswitchOffSignal2$Pvalue)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MACHINE._switchOffSignal2._value from %d to %d", $P$PRE$PMACHINE$PswitchOffSignal2$Pvalue, $PMACHINE$PswitchOffSignal2$Pvalue);
    needToIterate = 1;
  }
  if($PMACHINE$PswitchOffSignal3$Pvalue != $P$PRE$PMACHINE$PswitchOffSignal3$Pvalue)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: MACHINE._switchOffSignal3._value from %d to %d", $P$PRE$PMACHINE$PswitchOffSignal3$Pvalue, $PMACHINE$PswitchOffSignal3$Pvalue);
    needToIterate = 1;
  }
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  TRACE_POP
  return needToIterate;
}

#if defined(__cplusplus)
}
#endif

