//
// Copyright (c) 2015-2019, RTE (http://www.rte-france.com)
// See AUTHORS.txt
// All rights reserved.
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, you can obtain one at http://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0
//
// This file is part of Dynawo, an hybrid C++/Modelica open source time domain
// simulation tool for power systems.
//

/* Asserts */
/* Simulation code for MACHINE_PQ generated by the OpenModelica Compiler OMCompiler v1.9.4. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "MACHINE_PQ_functions.h"
#include "MACHINE_PQ_model.h"
#include "MACHINE_PQ_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif
#if defined(__cplusplus)
extern "C" {
#endif


/*
 equation index: 90
 type: ALGORITHM
 
   assert(MACHINE.state >= Dynawo.Electrical.Constants.state$MACHINE$state.OPEN and MACHINE.state <= Dynawo.Electrical.Constants.state$MACHINE$state.UNDEFINED, "Variable MACHINE.state out of [min, max] interval: MACHINE.state >= Dynawo.Electrical.Constants.state$MACHINE$state.OPEN and MACHINE.state <= Dynawo.Electrical.Constants.state$MACHINE$state.UNDEFINED has value: " + String(MACHINE.state, "d"));
 */
void MACHINE_PQ_eqFunction_90(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,90};
  modelica_boolean tmp10;
  modelica_boolean tmp11;
  static const MMC_DEFSTRINGLIT(tmp12,211,"Variable MACHINE.state out of [min, max] interval: MACHINE.state >= Dynawo.Electrical.Constants.state$MACHINE$state.OPEN and MACHINE.state <= Dynawo.Electrical.Constants.state$MACHINE$state.UNDEFINED has value: ");
  modelica_string tmp13;
  static int tmp14 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp14)
  {
    tmp10 = GreaterEq((modelica_integer)$PMACHINE$Pstate,1);
    tmp11 = LessEq((modelica_integer)$PMACHINE$Pstate,6);
    if(!(tmp10 && tmp11))
    {
      tmp13 = modelica_integer_to_modelica_string_format((modelica_integer)$PMACHINE$Pstate, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp12),tmp13);
      {
        FILE_INFO info = {"/home/rosiereflo/Projects/devBranch/dynawo/dynawo/install/gcc7/master/Release/dynawo/ddb/Dynawo/Electrical/Controls/Basics/SwitchOff.mo",61,5,61,72,0};
        omc_assert_warning(info, "The following assertion has been violated %sat time %f\nMACHINE.state >= Dynawo.Electrical.Constants.state$MACHINE$state.OPEN and MACHINE.state <= Dynawo.Electrical.Constants.state$MACHINE$state.UNDEFINED", initial() ? "during initialization " : "", data->localData[0]->timeValue);
        omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      }
      tmp14 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 91
 type: ALGORITHM
 
   assert(MACHINE.pStatus >= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.standard and MACHINE.pStatus <= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.limitPMax, "Variable MACHINE.pStatus out of [min, max] interval: MACHINE.pStatus >= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.standard and MACHINE.pStatus <= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.limitPMax has value: " + String(MACHINE.pStatus, "d"));
 */
void MACHINE_PQ_eqFunction_91(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,91};
  modelica_boolean tmp15;
  modelica_boolean tmp16;
  static const MMC_DEFSTRINGLIT(tmp17,251,"Variable MACHINE.pStatus out of [min, max] interval: MACHINE.pStatus >= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.standard and MACHINE.pStatus <= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.limitPMax has value: ");
  modelica_string tmp18;
  static int tmp19 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp19)
  {
    tmp15 = GreaterEq((modelica_integer)$PMACHINE$PpStatus,1);
    tmp16 = LessEq((modelica_integer)$PMACHINE$PpStatus,3);
    if(!(tmp15 && tmp16))
    {
      tmp18 = modelica_integer_to_modelica_string_format((modelica_integer)$PMACHINE$PpStatus, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp17),tmp18);
      {
        FILE_INFO info = {"/home/rosiereflo/Projects/devBranch/dynawo/dynawo/install/gcc7/master/Release/dynawo/ddb/Dynawo/Electrical/Machines/BaseClasses.mo",70,5,70,101,0};
        omc_assert_warning(info, "The following assertion has been violated %sat time %f\nMACHINE.pStatus >= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.standard and MACHINE.pStatus <= Dynawo.Electrical.Machines.GeneratorPQ.PStatus$MACHINE$pStatus.limitPMax", initial() ? "during initialization " : "", data->localData[0]->timeValue);
        omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      }
      tmp19 = 1;
    }
  }
  TRACE_POP
}
/*
 equation index: 92
 type: ALGORITHM
 
   assert(MACHINE.qStatus >= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.standard and MACHINE.qStatus <= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.generationMax, "Variable MACHINE.qStatus out of [min, max] interval: MACHINE.qStatus >= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.standard and MACHINE.qStatus <= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.generationMax has value: " + String(MACHINE.qStatus, "d"));
 */
void MACHINE_PQ_eqFunction_92(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,92};
  modelica_boolean tmp20;
  modelica_boolean tmp21;
  static const MMC_DEFSTRINGLIT(tmp22,255,"Variable MACHINE.qStatus out of [min, max] interval: MACHINE.qStatus >= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.standard and MACHINE.qStatus <= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.generationMax has value: ");
  modelica_string tmp23;
  static int tmp24 = 0;
  modelica_metatype tmpMeta[1] __attribute__((unused)) = {0};
  if(!tmp24)
  {
    tmp20 = GreaterEq((modelica_integer)$PMACHINE$PqStatus,1);
    tmp21 = LessEq((modelica_integer)$PMACHINE$PqStatus,3);
    if(!(tmp20 && tmp21))
    {
      tmp23 = modelica_integer_to_modelica_string_format((modelica_integer)$PMACHINE$PqStatus, (modelica_string) mmc_strings_len1[100]);
      tmpMeta[0] = stringAppend(MMC_REFSTRINGLIT(tmp22),tmp23);
      {
        FILE_INFO info = {"/home/rosiereflo/Projects/devBranch/dynawo/dynawo/install/gcc7/master/Release/dynawo/ddb/Dynawo/Electrical/Machines/GeneratorPQ.mo",42,5,42,113,0};
        omc_assert_warning(info, "The following assertion has been violated %sat time %f\nMACHINE.qStatus >= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.standard and MACHINE.qStatus <= Dynawo.Electrical.Machines.GeneratorPQ.QStatus$MACHINE$qStatus.generationMax", initial() ? "during initialization " : "", data->localData[0]->timeValue);
        omc_assert_warning_withEquationIndexes(info, equationIndexes, MMC_STRINGDATA(tmpMeta[0]));
      }
      tmp24 = 1;
    }
  }
  TRACE_POP
}
/* function to check assert after a step is done */
int MACHINE_PQ_checkForAsserts(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  MACHINE_PQ_eqFunction_90(data, threadData);

  MACHINE_PQ_eqFunction_91(data, threadData);

  MACHINE_PQ_eqFunction_92(data, threadData);
  
  TRACE_POP
  return 0;
}

#if defined(__cplusplus)
}
#endif

